db.restaurante.insertMany([
    { id_cliente: 1, nombre: 'Alex Martínez' , email: 'AlexMartínez@gmail.com', telefono: '(555) 123-4567', direccion: 'Calle 12 # 23-45, Pasto', fecha_registro: 'lunes, 15 de enero de 2024', fecha_ultima_visita: 'lunes, 5 de febrero de 2024', preferencia_de_mesa: 'Mesa_A1', total_gastado: 120000, comentarios: 'Excelente comida, volveré pronto.', fecha_nacimiento: 'martes, 15 de febrero de 1994' , tipo_cliente: 'VIP', edad: 30, numero_visitas: 5, numero_pedidos: 4, descuento_aplicado: 14250, tiempo_promedio_estancia: 1.15},																														
    { id_cliente: 2, nombre: 'Bianca Fernández' , email: 'BiancaFernández@gmail.com', telefono: '(555) 234-5678', direccion: 'Carrera 7 # 14-32, Pasto', fecha_registro: 'jueves, 22 de febrero de 2024', fecha_ultima_visita: 'jueves, 14 de marzo de 2024', preferencia_de_mesa: 'Mesa_B2', total_gastado: 250000, comentarios: 'Servicio muy atento, gracias.', fecha_nacimiento: 'miércoles, 21 de julio de 1993' , tipo_cliente: 'Frecuente', edad: 31, numero_visitas: 13, numero_pedidos: 17, descuento_aplicado: 28500, tiempo_promedio_estancia: 0.55},																														
    { id_cliente: 3, nombre: 'Carlos López' , email: 'CarlosLópez@gmail.com', telefono: '(555) 345-6789', direccion: 'Calle 18 # 30-21, Pasto', fecha_registro: 'domingo, 10 de marzo de 2024', fecha_ultima_visita: 'jueves, 25 de abril de 2024', preferencia_de_mesa: 'Mesa_C3', total_gastado: 180000, comentarios: 'La pasta estaba deliciosa.', fecha_nacimiento: 'martes, 30 de mayo de 1995' , tipo_cliente: 'Ocasional', edad: 29, numero_visitas: 8, numero_pedidos: 9, descuento_aplicado: 19000, tiempo_promedio_estancia: 1.30},																														
    { id_cliente: 4, nombre: 'Daniela Pérez' , email: 'DanielaPérez@gmail.com', telefono: '(555) 456-7890', direccion: 'Carrera 5 # 20-10, Pasto', fecha_registro: 'viernes, 5 de abril de 2024', fecha_ultima_visita: 'domingo, 19 de mayo de 2024', preferencia_de_mesa: 'Mesa_D4', total_gastado: 350000, comentarios: 'La atención fue rápida y eficiente.', fecha_nacimiento: 'jueves, 12 de noviembre de 1992' , tipo_cliente: 'Nuevo', edad: 31, numero_visitas: 17, numero_pedidos: 13, descuento_aplicado: 38000, tiempo_promedio_estancia: 2.10},																														
    { id_cliente: 5, nombre: 'Eduardo Sánchez' , email: 'EduardoSánchez@gmail.com', telefono: '(555) 567-8901', direccion: 'Calle 22 # 25-14, Pasto', fecha_registro: 'sábado, 18 de mayo de 2024', fecha_ultima_visita: 'sábado, 22 de junio de 2024', preferencia_de_mesa: 'Mesa_E5', total_gastado: 160000, comentarios: 'La ingeniera María es muy linda', fecha_nacimiento: 'martes, 18 de junio de 1991' , tipo_cliente: 'Regular', edad: 33, numero_visitas: 12, numero_pedidos: 6, descuento_aplicado: 15200, tiempo_promedio_estancia: 1.05},																														
    { id_cliente: 6, nombre: 'Fernanda Ruiz' , email: 'FernandaRuiz@gmail.com', telefono: '(555) 678-9012', direccion: 'Carrera 10 # 12-18, Pasto', fecha_registro: 'viernes, 23 de junio de 2023', fecha_ultima_visita: 'domingo, 30 de julio de 2023', preferencia_de_mesa: 'Mesa_F6', total_gastado: 200000, comentarios: 'La comida llegó fría, pero buena.', fecha_nacimiento: 'domingo, 25 de septiembre de 1994' , tipo_cliente: 'VIP', edad: 30, numero_visitas: 3, numero_pedidos: 15, descuento_aplicado: 23750, tiempo_promedio_estancia: 1.40},																														
    { id_cliente: 7, nombre: 'Gabriel Gómez' , email: 'GabrielGómez@gmail.com', telefono: '(555) 789-0123', direccion: 'Calle 7 # 17-30, Pasto', fecha_registro: 'domingo, 30 de julio de 2023', fecha_ultima_visita: 'viernes, 8 de septiembre de 2023', preferencia_de_mesa: 'Mesa_G7', total_gastado: 220000, comentarios: 'Muy buen lugar para cenar.', fecha_nacimiento: 'lunes, 3 de abril de 1995' , tipo_cliente: 'Frecuente', edad: 29, numero_visitas: 19, numero_pedidos: 10, descuento_aplicado: 20900, tiempo_promedio_estancia: 0.50},																														
    { id_cliente: 8, nombre: 'Helena Morales' , email: 'HelenaMorales@gmail.com', telefono: '(555) 890-1234', direccion: 'Carrera 8 # 21-40, Pasto', fecha_registro: 'lunes, 14 de agosto de 2023', fecha_ultima_visita: 'martes, 17 de octubre de 2023', preferencia_de_mesa: 'Mesa_H8', total_gastado: 300000, comentarios: 'Un poco caro, pero vale la pena.', fecha_nacimiento: 'martes, 7 de agosto de 1990' , tipo_cliente: 'Ocasional', edad: 34, numero_visitas: 14, numero_pedidos: 12, descuento_aplicado: 33250, tiempo_promedio_estancia: 1.20},																														
    { id_cliente: 9, nombre: 'Iván Torres' , email: 'IvánTorres@gmail.com', telefono: '(555) 901-2345', direccion: 'Calle 16 # 24-15, Pasto', fecha_registro: 'jueves, 7 de septiembre de 2023', fecha_ultima_visita: 'miércoles, 15 de noviembre de 2023', preferencia_de_mesa: 'Mesa_I9', total_gastado: 450000, comentarios: 'El postre fue el mejor.', fecha_nacimiento: 'martes, 29 de diciembre de 1992' , tipo_cliente: 'Nuevo', edad: 31, numero_visitas: 7, numero_pedidos: 19, descuento_aplicado: 42750, tiempo_promedio_estancia: 1.55},																														
    { id_cliente: 10, nombre: 'Julia Ramírez' , email: 'JuliaRamírez@gmail.com', telefono: '(555) 012-3456', direccion: 'Carrera 6 # 22-28, Pasto', fecha_registro: 'jueves, 19 de octubre de 2023', fecha_ultima_visita: 'martes, 26 de diciembre de 2023', preferencia_de_mesa: 'Mesa_J10', total_gastado: 80000, comentarios: 'Las mesas estaban muy limpias.', fecha_nacimiento: 'martes, 16 de marzo de 1993' , tipo_cliente: 'Regular', edad: 31, numero_visitas: 15, numero_pedidos: 2, descuento_aplicado: 7600, tiempo_promedio_estancia: 0.45},																														
    { id_cliente: 11, nombre: 'Kevin Ortega' , email: 'KevinOrtega@gmail.com', telefono: '(555) 123-4568', direccion: 'Calle 15 # 10-20, Pasto', fecha_registro: 'domingo, 26 de noviembre de 2023', fecha_ultima_visita: 'lunes, 30 de enero de 2023', preferencia_de_mesa: 'Mesa_K11', total_gastado: 270000, comentarios: 'La carne estaba en su punto.', fecha_nacimiento: 'miércoles, 23 de octubre de 1991' , tipo_cliente: 'VIP', edad: 32, numero_visitas: 10, numero_pedidos: 14, descuento_aplicado: 25650, tiempo_promedio_estancia: 1.25},																														
    { id_cliente: 12, nombre: 'Laura Castro' , email: 'LauraCastro@gmail.com', telefono: '(555) 234-5679', direccion: 'Carrera 9 # 18-11, Pasto', fecha_registro: 'lunes, 11 de diciembre de 2023', fecha_ultima_visita: 'sábado, 25 de febrero de 2023', preferencia_de_mesa: 'Mesa_L12', total_gastado: 150000, comentarios: 'Me gustó el menú variado.', fecha_nacimiento: 'viernes, 14 de enero de 1994' , tipo_cliente: 'Frecuente', edad: 30, numero_visitas: 18, numero_pedidos: 8, descuento_aplicado: 17100, tiempo_promedio_estancia: 1.10},																														
    { id_cliente: 13, nombre: 'Manuel García' , email: 'ManuelGarcía@gmail.com', telefono: '(555) 345-6780', direccion: 'Calle 11 # 14-34, Pasto', fecha_registro: 'sábado, 29 de enero de 2022', fecha_ultima_visita: 'domingo, 2 de abril de 2023', preferencia_de_mesa: 'Mesa_M13', total_gastado: 320000, comentarios: 'El lugar es acogedor.', fecha_nacimiento: 'lunes, 26 de junio de 1995' , tipo_cliente: 'Ocasional', edad: 29, numero_visitas: 6, numero_pedidos: 16, descuento_aplicado: 30400, tiempo_promedio_estancia: 2.00},																														
    { id_cliente: 14, nombre: 'Natalia Delgado' , email: 'NataliaDelgado@gmail.com', telefono: '(555) 456-7891', direccion: 'Carrera 4 # 16-22, Pasto', fecha_registro: 'viernes, 18 de febrero de 2022', fecha_ultima_visita: 'jueves, 11 de mayo de 2023', preferencia_de_mesa: 'Mesa_N14', total_gastado: 140000, comentarios: 'Buenas porciones y calidad.', fecha_nacimiento: 'jueves, 9 de julio de 1992' , tipo_cliente: 'Nuevo', edad: 32, numero_visitas: 11, numero_pedidos: 7, descuento_aplicado: 13300, tiempo_promedio_estancia: 0.40},																														
    { id_cliente: 15, nombre: 'Óscar Mendoza' , email: 'ÓscarMendoza@gmail.com', telefono: '(555) 567-8902', direccion: 'Calle 20 # 30-11, Pasto', fecha_registro: 'lunes, 14 de marzo de 2022', fecha_ultima_visita: 'domingo, 18 de junio de 2023', preferencia_de_mesa: 'Mesa_O15', total_gastado: 240000, comentarios: 'No me gustó el trato del camarero.', fecha_nacimiento: 'sábado, 15 de diciembre de 1990' , tipo_cliente: 'Regular', edad: 33, numero_visitas: 9, numero_pedidos: 11, descuento_aplicado: 22800, tiempo_promedio_estancia: 1.35},																														
    { id_cliente: 16, nombre: 'Paula Castro' , email: 'PaulaCastro@gmail.com', telefono: '(555) 678-9013', direccion: 'Carrera 3 # 19-25, Pasto', fecha_registro: 'lunes, 25 de abril de 2022', fecha_ultima_visita: 'sábado, 5 de agosto de 2023', preferencia_de_mesa: 'Mesa_P16', total_gastado: 400000, comentarios: 'El ambiente es perfecto para una cena romántica.', fecha_nacimiento: 'domingo, 28 de febrero de 1993' , tipo_cliente: 'VIP', edad: 31, numero_visitas: 20, numero_pedidos: 18, descuento_aplicado: 38000, tiempo_promedio_estancia: 1.50},																														
    { id_cliente: 17, nombre: 'Quentin Romero' , email: 'QuentinRomero@gmail.com', telefono: '(555) 789-0124', direccion: 'Calle 13 # 22-18, Pasto', fecha_registro: 'lunes, 9 de mayo de 2022', fecha_ultima_visita: 'martes, 12 de septiembre de 2023', preferencia_de_mesa: 'Mesa_Q17', total_gastado: 90000, comentarios: 'La comida llegó a tiempo.', fecha_nacimiento: 'martes, 5 de noviembre de 1991' , tipo_cliente: 'Frecuente', edad: 32, numero_visitas: 4, numero_pedidos: 3, descuento_aplicado: 9500, tiempo_promedio_estancia: 0.35},																														
    { id_cliente: 18, nombre: 'Raquel Vázquez' , email: 'RaquelVázquez@gmail.com', telefono: '(555) 890-1235', direccion: 'Carrera 11 # 10-14, Pasto', fecha_registro: 'jueves, 16 de junio de 2022', fecha_ultima_visita: 'miércoles, 25 de octubre de 2023', preferencia_de_mesa: 'Mesa_R18', total_gastado: 480000, comentarios: 'El personal es muy amable.', fecha_nacimiento: 'domingo, 14 de agosto de 1994' , tipo_cliente: 'Ocasional', edad: 30, numero_visitas: 16, numero_pedidos: 20, descuento_aplicado: 45600, tiempo_promedio_estancia: 2.15},																														
    { id_cliente: 19, nombre: 'Sergio Jiménez' , email: 'SergioJiménez@gmail.com', telefono: '(555) 901-2346', direccion: 'Calle 9 # 17-32, Pasto', fecha_registro: 'jueves, 21 de julio de 2022', fecha_ultima_visita: 'jueves, 9 de noviembre de 2023', preferencia_de_mesa: 'Mesa_S19', total_gastado: 110000, comentarios: 'La pizza fue excelente.', fecha_nacimiento: 'miércoles, 22 de marzo de 1995' , tipo_cliente: 'Nuevo', edad: 29, numero_visitas: 2, numero_pedidos: 5, descuento_aplicado: 10450, tiempo_promedio_estancia: 1.00},																														
    { id_cliente: 20, nombre: 'Teresa Salazar' , email: 'TeresaSalazar@gmail.com', telefono: '(555) 012-3457', direccion: 'Carrera 12 # 21-13, Pasto', fecha_registro: 'martes, 30 de agosto de 2022', fecha_ultima_visita: 'miércoles, 20 de diciembre de 2023', preferencia_de_mesa: 'Mesa_T20', total_gastado: 350000, comentarios: 'Deberían mejorar la música ambiente.', fecha_nacimiento: 'domingo, 11 de octubre de 1992' , tipo_cliente: 'Regular', edad: 31, numero_visitas: 13, numero_pedidos: 13, descuento_aplicado: 36100, tiempo_promedio_estancia: 1.45},																														
    { id_cliente: 21, nombre: 'Ulises Hernández' , email: 'UlisesHernández@gmail.com', telefono: '(555) 123-4569', direccion: 'Calle 21 # 28-17, Pasto', fecha_registro: 'sábado, 17 de septiembre de 2022', fecha_ultima_visita: 'sábado, 12 de febrero de 2022', preferencia_de_mesa: 'Mesa_A1', total_gastado: 300000, comentarios: 'El lugar es muy cómodo.', fecha_nacimiento: 'lunes, 3 de septiembre de 1990' , tipo_cliente: 'VIP', edad: 34, numero_visitas: 8, numero_pedidos: 12, descuento_aplicado: 28500, tiempo_promedio_estancia: 1.10},																														
    { id_cliente: 22, nombre: 'Vanessa Soto' , email: 'VanessaSoto@gmail.com', telefono: '(555) 234-5680', direccion: 'Carrera 2 # 15-20, Pasto', fecha_registro: 'miércoles, 12 de octubre de 2022', fecha_ultima_visita: 'sábado, 19 de marzo de 2022', preferencia_de_mesa: 'Mesa_B2', total_gastado: 150000, comentarios: 'La sopa estaba demasiado salada.', fecha_nacimiento: 'lunes, 19 de abril de 1993' , tipo_cliente: 'Frecuente', edad: 31, numero_visitas: 14, numero_pedidos: 9, descuento_aplicado: 15200, tiempo_promedio_estancia: 0.50},																														
    { id_cliente: 23, nombre: 'William Vargas' , email: 'WilliamVargas@gmail.com', telefono: '(555) 345-6781', direccion: 'Calle 8 # 12-28, Pasto', fecha_registro: 'lunes, 7 de noviembre de 2022', fecha_ultima_visita: 'jueves, 28 de abril de 2022', preferencia_de_mesa: 'Mesa_C3', total_gastado: 270000, comentarios: 'El servicio fue un poco lento.', fecha_nacimiento: 'martes, 28 de mayo de 1991' , tipo_cliente: 'Ocasional', edad: 33, numero_visitas: 7, numero_pedidos: 17, descuento_aplicado: 26600, tiempo_promedio_estancia: 2.05},																														
    { id_cliente: 24, nombre: 'Ximena Aguilar' , email: 'XimenaAguilar@gmail.com', telefono: '(555) 456-7892', direccion: 'Carrera 1 # 18-25, Pasto', fecha_registro: 'sábado, 24 de diciembre de 2022', fecha_ultima_visita: 'miércoles, 15 de junio de 2022', preferencia_de_mesa: 'Mesa_D4', total_gastado: 200000, comentarios: 'Me sorprendió la calidad de los ingredientes.', fecha_nacimiento: 'lunes, 20 de junio de 1994' , tipo_cliente: 'Nuevo', edad: 30, numero_visitas: 19, numero_pedidos: 6, descuento_aplicado: 19000, tiempo_promedio_estancia: 1.15},																														
    { id_cliente: 25, nombre: 'Yahir Jiménez' , email: 'YahirJiménez@gmail.com', telefono: '(555) 567-8903', direccion: 'Calle 23 # 30-40, Pasto', fecha_registro: 'miércoles, 20 de enero de 2021', fecha_ultima_visita: 'miércoles, 20 de julio de 2022', preferencia_de_mesa: 'Mesa_E5', total_gastado: 220000, comentarios: 'El vino estaba exquisito.', fecha_nacimiento: 'domingo, 30 de julio de 1995' , tipo_cliente: 'Regular', edad: 29, numero_visitas: 12, numero_pedidos: 10, descuento_aplicado: 21850, tiempo_promedio_estancia: 1.30},																														
    { id_cliente: 26, nombre: 'Zara Morales' , email: 'ZaraMorales@gmail.com', telefono: '(555) 678-9014', direccion: 'Carrera 13 # 22-12, Pasto', fecha_registro: 'viernes, 12 de febrero de 2021', fecha_ultima_visita: 'miércoles, 31 de agosto de 2022', preferencia_de_mesa: 'Mesa_F6', total_gastado: 320000, comentarios: 'Buena relación calidad-precio.', fecha_nacimiento: 'miércoles, 12 de febrero de 1992' , tipo_cliente: 'VIP', edad: 32, numero_visitas: 3, numero_pedidos: 15, descuento_aplicado: 33250, tiempo_promedio_estancia: 0.55},																														
    { id_cliente: 27, nombre: 'Adrian Gómez' , email: 'AdrianGómez@gmail.com', telefono: '(555) 789-0125', direccion: 'Calle 19 # 25-15, Pasto', fecha_registro: 'sábado, 27 de marzo de 2021', fecha_ultima_visita: 'viernes, 14 de octubre de 2022', preferencia_de_mesa: 'Mesa_G7', total_gastado: 120000, comentarios: 'Muy recomendable para grupos grandes.', fecha_nacimiento: 'viernes, 16 de noviembre de 1990' , tipo_cliente: 'Frecuente', edad: 33, numero_visitas: 17, numero_pedidos: 4, descuento_aplicado: 17100, tiempo_promedio_estancia: 1.40},																														
    { id_cliente: 28, nombre: 'Beatriz López' , email: 'BeatrizLópez@gmail.com', telefono: '(555) 890-1236', direccion: 'Carrera 15 # 20-18, Pasto', fecha_registro: 'miércoles, 14 de abril de 2021', fecha_ultima_visita: 'martes, 22 de noviembre de 2022', preferencia_de_mesa: 'Mesa_H8', total_gastado: 450000, comentarios: 'La comida es sabrosa, pero el lugar es ruidoso.', fecha_nacimiento: 'domingo, 5 de diciembre de 1993' , tipo_cliente: 'Ocasional', edad: 30, numero_visitas: 10, numero_pedidos: 19, descuento_aplicado: 41800, tiempo_promedio_estancia: 2.20},																														
    { id_cliente: 29, nombre: 'Claudio Fernández' , email: 'ClaudioFernández@gmail.com', telefono: '(555) 901-2347', direccion: 'Calle 14 # 17-25, Pasto', fecha_registro: 'sábado, 22 de mayo de 2021', fecha_ultima_visita: 'sábado, 10 de diciembre de 2022', preferencia_de_mesa: 'Mesa_I9', total_gastado: 160000, comentarios: 'El aperitivo estuvo muy bien.', fecha_nacimiento: 'domingo, 22 de septiembre de 1991' , tipo_cliente: 'Nuevo', edad: 32, numero_visitas: 15, numero_pedidos: 8, descuento_aplicado: 16150, tiempo_promedio_estancia: 1.25},																														
    { id_cliente: 30, nombre: 'Diana Moreno' , email: 'DianaMoreno@gmail.com', telefono: '(555) 012-3458', direccion: 'Carrera 16 # 24-10, Pasto', fecha_registro: 'miércoles, 30 de junio de 2021', fecha_ultima_visita: 'domingo, 30 de enero de 2022', preferencia_de_mesa: 'Mesa_J10', total_gastado: 240000, comentarios: 'La comida no cumplió mis expectativas.', fecha_nacimiento: 'martes, 17 de mayo de 1994' , tipo_cliente: 'Regular', edad: 30, numero_visitas: 6, numero_pedidos: 11, descuento_aplicado: 20900, tiempo_promedio_estancia: 1.05},																														
    { id_cliente: 31, nombre: 'Enrique Rivera' , email: 'EnriqueRivera@gmail.com', telefono: '(555) 123-4570', direccion: 'Calle 17 # 30-22, Pasto', fecha_registro: 'lunes, 19 de julio de 2021', fecha_ultima_visita: 'sábado, 5 de marzo de 2022', preferencia_de_mesa: 'Mesa_K11', total_gastado: 480000, comentarios: 'Las ensaladas estaban frescas y ricas.', fecha_nacimiento: 'lunes, 2 de octubre de 1995' , tipo_cliente: 'VIP', edad: 29, numero_visitas: 11, numero_pedidos: 20, descuento_aplicado: 45600, tiempo_promedio_estancia: 1.50},																														
    { id_cliente: 32, nombre: 'Francisca Ruiz' , email: 'FranciscaRuiz@gmail.com', telefono: '(555) 234-5681', direccion: 'Carrera 17 # 12-18, Pasto', fecha_registro: 'domingo, 8 de agosto de 2021', fecha_ultima_visita: 'martes, 12 de abril de 2022', preferencia_de_mesa: 'Mesa_L12', total_gastado: 90000, comentarios: 'Me gustó la decoración del restaurante.', fecha_nacimiento: 'lunes, 9 de marzo de 1992' , tipo_cliente: 'Frecuente', edad: 32, numero_visitas: 20, numero_pedidos: 3, descuento_aplicado: 11400, tiempo_promedio_estancia: 0.45},																														
    { id_cliente: 33, nombre: 'Gonzalo Ortega' , email: 'GonzaloOrtega@gmail.com', telefono: '(555) 345-6782', direccion: 'Calle 10 # 15-20, Pasto', fecha_registro: 'jueves, 23 de septiembre de 2021', fecha_ultima_visita: 'domingo, 22 de mayo de 2022', preferencia_de_mesa: 'Mesa_M13', total_gastado: 350000, comentarios: 'La atención fue excelente.', fecha_nacimiento: 'jueves, 21 de junio de 1990' , tipo_cliente: 'Ocasional', edad: 34, numero_visitas: 4, numero_pedidos: 14, descuento_aplicado: 36100, tiempo_promedio_estancia: 2.00},																														
    { id_cliente: 34, nombre: 'Hilda Torres' , email: 'HildaTorres@gmail.com', telefono: '(555) 456-7893', direccion: 'Carrera 18 # 23-30, Pasto', fecha_registro: 'lunes, 11 de octubre de 2021', fecha_ultima_visita: 'domingo, 10 de julio de 2022', preferencia_de_mesa: 'Mesa_N14', total_gastado: 140000, comentarios: 'La hamburguesa estaba muy buena.', fecha_nacimiento: 'jueves, 15 de julio de 1993' , tipo_cliente: 'Nuevo', edad: 31, numero_visitas: 18, numero_pedidos: 7, descuento_aplicado: 13300, tiempo_promedio_estancia: 1.10},																														
    { id_cliente: 35, nombre: 'Ignacio Silva' , email: 'IgnacioSilva@gmail.com', telefono: '(555) 567-8904', direccion: 'Calle 6 # 28-11, Pasto', fecha_registro: 'martes, 2 de noviembre de 2021', fecha_ultima_visita: 'miércoles, 24 de agosto de 2022', preferencia_de_mesa: 'Mesa_O15', total_gastado: 400000, comentarios: 'El menú es variado y sabroso.', fecha_nacimiento: 'domingo, 8 de diciembre de 1991' , tipo_cliente: 'Regular', edad: 32, numero_visitas: 5, numero_pedidos: 16, descuento_aplicado: 39900, tiempo_promedio_estancia: 1.55},																														
    { id_cliente: 36, nombre: 'Juana Morales' , email: 'JuanaMorales@gmail.com', telefono: '(555) 678-9015', direccion: 'Carrera 19 # 21-14, Pasto', fecha_registro: 'domingo, 19 de diciembre de 2021', fecha_ultima_visita: 'sábado, 1 de octubre de 2022', preferencia_de_mesa: 'Mesa_P16', total_gastado: 80000, comentarios: 'La experiencia fue buena en general.', fecha_nacimiento: 'miércoles, 2 de noviembre de 1994' , tipo_cliente: 'VIP', edad: 30, numero_visitas: 16, numero_pedidos: 2, descuento_aplicado: 8550, tiempo_promedio_estancia: 0.50},																														
    { id_cliente: 37, nombre: 'Klaus Müller' , email: 'KlausMüller@gmail.com', telefono: '(555) 789-0126', direccion: 'Calle 24 # 10-18, Pasto', fecha_registro: 'martes, 7 de enero de 2020', fecha_ultima_visita: 'viernes, 18 de noviembre de 2022', preferencia_de_mesa: 'Mesa_Q17', total_gastado: 320000, comentarios: 'El café es muy rico.', fecha_nacimiento: 'viernes, 20 de enero de 1995' , tipo_cliente: 'Frecuente', edad: 29, numero_visitas: 9, numero_pedidos: 18, descuento_aplicado: 32300, tiempo_promedio_estancia: 1.35},																														
    { id_cliente: 38, nombre: 'Laura Jiménez' , email: 'LauraJiménez@gmail.com', telefono: '(555) 890-1237', direccion: 'Carrera 20 # 30-22, Pasto', fecha_registro: 'martes, 25 de febrero de 2020', fecha_ultima_visita: 'jueves, 29 de diciembre de 2022', preferencia_de_mesa: 'Mesa_R18', total_gastado: 70000, comentarios: 'El lugar se ve un poco descuidado.', fecha_nacimiento: 'sábado, 25 de abril de 1992' , tipo_cliente: 'Ocasional', edad: 32, numero_visitas: 2, numero_pedidos: 5, descuento_aplicado: 6650, tiempo_promedio_estancia: 2.10},																														
    { id_cliente: 39, nombre: 'Marcos Núñez' , email: 'MarcosNúñez@gmail.com', telefono: '(555) 901-2348', direccion: 'Calle 5 # 20-25, Pasto', fecha_registro: 'lunes, 16 de marzo de 2020', fecha_ultima_visita: 'martes, 26 de enero de 2021', preferencia_de_mesa: 'Mesa_S19', total_gastado: 350000, comentarios: 'La comida es siempre consistente.', fecha_nacimiento: 'martes, 17 de julio de 1990' , tipo_cliente: 'Nuevo', edad: 34, numero_visitas: 13, numero_pedidos: 13, descuento_aplicado: 38000, tiempo_promedio_estancia: 0.40},																														
    { id_cliente: 40, nombre: 'Nora Fernández' , email: 'NoraFernández@gmail.com', telefono: '(555) 012-3459', direccion: 'Carrera 21 # 22-30, Pasto', fecha_registro: 'martes, 21 de abril de 2020', fecha_ultima_visita: 'miércoles, 3 de marzo de 2021', preferencia_de_mesa: 'Mesa_T20', total_gastado: 150000, comentarios: 'Los precios son un poco altos.', fecha_nacimiento: 'domingo, 23 de mayo de 1993' , tipo_cliente: 'Regular', edad: 31, numero_visitas: 7, numero_pedidos: 12, descuento_aplicado: 18050, tiempo_promedio_estancia: 1.20},																														
    { id_cliente: 41, nombre: 'Omar Reyes' , email: 'OmarReyes@gmail.com', telefono: '(555) 123-4571', direccion: 'Calle 2 # 12-24, Pasto', fecha_registro: 'sábado, 30 de mayo de 2020', fecha_ultima_visita: 'martes, 20 de abril de 2021', preferencia_de_mesa: 'Mesa_A1', total_gastado: 300000, comentarios: 'El ambiente es muy agradable.', fecha_nacimiento: 'martes, 13 de agosto de 1991' , tipo_cliente: 'VIP', edad: 33, numero_visitas: 14, numero_pedidos: 9, descuento_aplicado: 28500, tiempo_promedio_estancia: 1.00},																														
    { id_cliente: 42, nombre: 'Pilar Martínez' , email: 'PilarMartínez@gmail.com', telefono: '(555) 234-5682', direccion: 'Carrera 22 # 19-14, Pasto', fecha_registro: 'lunes, 15 de junio de 2020', fecha_ultima_visita: 'sábado, 12 de junio de 2021', preferencia_de_mesa: 'Mesa_B2', total_gastado: 480000, comentarios: 'El servicio fue rápido y eficiente.', fecha_nacimiento: 'sábado, 19 de marzo de 1994' , tipo_cliente: 'Frecuente', edad: 30, numero_visitas: 17, numero_pedidos: 20, descuento_aplicado: 47500, tiempo_promedio_estancia: 1.45},																														
    { id_cliente: 43, nombre: 'Rodrigo Soto' , email: 'RodrigoSoto@gmail.com', telefono: '(555) 345-6783', direccion: 'Calle 4 # 28-17, Pasto', fecha_registro: 'viernes, 10 de julio de 2020', fecha_ultima_visita: 'viernes, 30 de julio de 2021', preferencia_de_mesa: 'Mesa_C3', total_gastado: 220000, comentarios: 'La comida estaba demasiado picante.', fecha_nacimiento: 'martes, 12 de septiembre de 1995' , tipo_cliente: 'Ocasional', edad: 29, numero_visitas: 8, numero_pedidos: 15, descuento_aplicado: 19000, tiempo_promedio_estancia: 2.25},																														
    { id_cliente: 44, nombre: 'Silvia Mendoza' , email: 'SilviaMendoza@gmail.com', telefono: '(555) 456-7894', direccion: 'Carrera 23 # 16-20, Pasto', fecha_registro: 'jueves, 27 de agosto de 2020', fecha_ultima_visita: 'martes, 14 de septiembre de 2021', preferencia_de_mesa: 'Mesa_D4', total_gastado: 200000, comentarios: 'La experiencia fue muy positiva.', fecha_nacimiento: 'lunes, 27 de enero de 1992' , tipo_cliente: 'Nuevo', edad: 32, numero_visitas: 19, numero_pedidos: 10, descuento_aplicado: 20900, tiempo_promedio_estancia: 1.30},																														
    { id_cliente: 45, nombre: 'Tomás Ortega' , email: 'TomásOrtega@gmail.com', telefono: '(555) 567-8905', direccion: 'Calle 1 # 14-30, Pasto', fecha_registro: 'sábado, 12 de septiembre de 2020', fecha_ultima_visita: 'lunes, 25 de octubre de 2021', preferencia_de_mesa: 'Mesa_E5', total_gastado: 110000, comentarios: 'La carne no estaba bien cocida.', fecha_nacimiento: 'jueves, 4 de octubre de 1990' , tipo_cliente: 'Regular', edad: 34, numero_visitas: 12, numero_pedidos: 6, descuento_aplicado: 11400, tiempo_promedio_estancia: 0.55},																														
    { id_cliente: 46, nombre: 'Úrsula Castro' , email: 'ÚrsulaCastro@gmail.com', telefono: '(555) 678-9016', direccion: 'Carrera 24 # 25-22, Pasto', fecha_registro: 'jueves, 22 de octubre de 2020', fecha_ultima_visita: 'miércoles, 1 de diciembre de 2021', preferencia_de_mesa: 'Mesa_F6', total_gastado: 120000, comentarios: 'El lugar tiene un buen diseño.', fecha_nacimiento: 'viernes, 10 de septiembre de 1993' , tipo_cliente: 'VIP', edad: 31, numero_visitas: 3, numero_pedidos: 4, descuento_aplicado: 13300, tiempo_promedio_estancia: 1.20},																														
    { id_cliente: 47, nombre: 'Víctor Romero' , email: 'VíctorRomero@gmail.com', telefono: '(555) 789-0127', direccion: 'Calle 3 # 10-18, Pasto', fecha_registro: 'lunes, 9 de noviembre de 2020', fecha_ultima_visita: 'jueves, 14 de enero de 2021', preferencia_de_mesa: 'Mesa_G7', total_gastado: 250000, comentarios: 'Los postres son deliciosos.', fecha_nacimiento: 'lunes, 22 de abril de 1991' , tipo_cliente: 'Frecuente', edad: 33, numero_visitas: 15, numero_pedidos: 17, descuento_aplicado: 29450, tiempo_promedio_estancia: 1.50},																														
    { id_cliente: 48, nombre: 'Wendy López' , email: 'WendyLópez@gmail.com', telefono: '(555) 890-1238', direccion: 'Carrera 25 # 22-14, Pasto', fecha_registro: 'sábado, 5 de diciembre de 2020', fecha_ultima_visita: 'domingo, 28 de febrero de 2021', preferencia_de_mesa: 'Mesa_H8', total_gastado: 140000, comentarios: 'La comida llegó fría.', fecha_nacimiento: 'sábado, 17 de diciembre de 1994' , tipo_cliente: 'Ocasional', edad: 29, numero_visitas: 10, numero_pedidos: 8, descuento_aplicado: 15200, tiempo_promedio_estancia: 2.00},																														
    { id_cliente: 49, nombre: 'Xavier Vargas' , email: 'XavierVargas@gmail.com', telefono: '(555) 901-2349', direccion: 'Calle 26 # 30-10, Pasto', fecha_registro: 'viernes, 25 de enero de 2019', fecha_ultima_visita: 'jueves, 8 de abril de 2021', preferencia_de_mesa: 'Mesa_I9', total_gastado: 240000, comentarios: 'El servicio al cliente es excelente.', fecha_nacimiento: 'domingo, 6 de agosto de 1995' , tipo_cliente: 'Nuevo', edad: 29, numero_visitas: 11, numero_pedidos: 11, descuento_aplicado: 23750, tiempo_promedio_estancia: 1.05},																														
    { id_cliente: 50, nombre: 'Yolanda Gómez' , email: 'YolandaGómez@gmail.com', telefono: '(555) 012-3460', direccion: 'Carrera 26 # 18-25, Pasto', fecha_registro: 'jueves, 14 de febrero de 2019', fecha_ultima_visita: 'sábado, 22 de mayo de 2021', preferencia_de_mesa: 'Mesa_J10', total_gastado: 70000, comentarios: 'La comida es siempre fresca.', fecha_nacimiento: 'martes, 30 de junio de 1992' , tipo_cliente: 'Regular', edad: 32, numero_visitas: 6, numero_pedidos: 3, descuento_aplicado: 5700, tiempo_promedio_estancia: 0.45},																														
    { id_cliente: 51, nombre: 'Álvaro Pérez' , email: 'ÁlvaroPérez@gmail.com', telefono: '(555) 123-4572', direccion: 'Calle 27 # 12-22, Pasto', fecha_registro: 'viernes, 8 de marzo de 2019', fecha_ultima_visita: 'miércoles, 7 de julio de 2021', preferencia_de_mesa: 'Mesa_K11', total_gastado: 400000, comentarios: 'Las porciones son muy generosas.', fecha_nacimiento: 'lunes, 14 de mayo de 1990' , tipo_cliente: 'VIP', edad: 34, numero_visitas: 20, numero_pedidos: 18, descuento_aplicado: 42750, tiempo_promedio_estancia: 1.35},																														
    { id_cliente: 52, nombre: 'Bárbara Rodríguez' , email: 'BárbaraRodríguez@gmail.com', telefono: '(555) 234-5683', direccion: 'Carrera 27 # 20-18, Pasto', fecha_registro: 'miércoles, 17 de abril de 2019', fecha_ultima_visita: 'miércoles, 18 de agosto de 2021', preferencia_de_mesa: 'Mesa_L12', total_gastado: 80000, comentarios: 'El ambiente es tranquilo.', fecha_nacimiento: 'lunes, 11 de enero de 1993' , tipo_cliente: 'Frecuente', edad: 31, numero_visitas: 4, numero_pedidos: 2, descuento_aplicado: 7600, tiempo_promedio_estancia: 2.15},																														
    { id_cliente: 53, nombre: 'César Díaz' , email: 'CésarDíaz@gmail.com', telefono: '(555) 345-6784', direccion: 'Calle 28 # 17-30, Pasto', fecha_registro: 'viernes, 24 de mayo de 2019', fecha_ultima_visita: 'domingo, 3 de octubre de 2021', preferencia_de_mesa: 'Mesa_M13', total_gastado: 450000, comentarios: 'La comida tiene buen sabor.', fecha_nacimiento: 'viernes, 29 de marzo de 1991' , tipo_cliente: 'Ocasional', edad: 33, numero_visitas: 18, numero_pedidos: 19, descuento_aplicado: 47500, tiempo_promedio_estancia: 0.55},																														
    { id_cliente: 54, nombre: 'Daniela Ruiz' , email: 'DanielaRuiz@gmail.com', telefono: '(555) 456-7895', direccion: 'Carrera 28 # 14-21, Pasto', fecha_registro: 'miércoles, 12 de junio de 2019', fecha_ultima_visita: 'lunes, 15 de noviembre de 2021', preferencia_de_mesa: 'Mesa_N14', total_gastado: 180000, comentarios: 'La presentación de los platos es atractiva.', fecha_nacimiento: 'sábado, 23 de julio de 1994' , tipo_cliente: 'Nuevo', edad: 30, numero_visitas: 5, numero_pedidos: 14, descuento_aplicado: 19000, tiempo_promedio_estancia: 1.50},																														
    { id_cliente: 55, nombre: 'Esteban Castro' , email: 'EstebanCastro@gmail.com', telefono: '(555) 567-8906', direccion: 'Calle 29 # 25-22, Pasto', fecha_registro: 'miércoles, 31 de julio de 2019', fecha_ultima_visita: 'martes, 28 de diciembre de 2021', preferencia_de_mesa: 'Mesa_O15', total_gastado: 90000, comentarios: 'El lugar es ideal para cenas familiares.', fecha_nacimiento: 'sábado, 18 de febrero de 1995' , tipo_cliente: 'Regular', edad: 29, numero_visitas: 16, numero_pedidos: 5, descuento_aplicado: 10450, tiempo_promedio_estancia: 2.05},																														
    { id_cliente: 56, nombre: 'Fabiola Martínez' , email: 'FabiolaMartínez@gmail.com', telefono: '(555) 678-9017', direccion: 'Carrera 29 # 12-10, Pasto', fecha_registro: 'martes, 20 de agosto de 2019', fecha_ultima_visita: 'sábado, 15 de febrero de 2020', preferencia_de_mesa: 'Mesa_P16', total_gastado: 150000, comentarios: 'El menú es muy creativo.', fecha_nacimiento: 'miércoles, 12 de agosto de 1992' , tipo_cliente: 'VIP', edad: 32, numero_visitas: 9, numero_pedidos: 12, descuento_aplicado: 17100, tiempo_promedio_estancia: 1.10},																														
    { id_cliente: 57, nombre: 'Gonzalo Sánchez' , email: 'GonzaloSánchez@gmail.com', telefono: '(555) 789-0128', direccion: 'Calle 30 # 28-17, Pasto', fecha_registro: 'lunes, 9 de septiembre de 2019', fecha_ultima_visita: 'martes, 24 de marzo de 2020', preferencia_de_mesa: 'Mesa_Q17', total_gastado: 320000, comentarios: 'Las bebidas podrían mejorar.', fecha_nacimiento: 'jueves, 5 de abril de 1990' , tipo_cliente: 'Frecuente', edad: 34, numero_visitas: 2, numero_pedidos: 16, descuento_aplicado: 32300, tiempo_promedio_estancia: 0.50},																														
    { id_cliente: 58, nombre: 'Hugo Fernández' , email: 'HugoFernández@gmail.com', telefono: '(555) 890-1239', direccion: 'Carrera 30 # 22-30, Pasto', fecha_registro: 'martes, 29 de octubre de 2019', fecha_ultima_visita: 'lunes, 18 de mayo de 2020', preferencia_de_mesa: 'Mesa_R18', total_gastado: 140000, comentarios: 'La experiencia fue muy satisfactoria.', fecha_nacimiento: 'martes, 8 de junio de 1993' , tipo_cliente: 'Ocasional', edad: 31, numero_visitas: 13, numero_pedidos: 7, descuento_aplicado: 12350, tiempo_promedio_estancia: 1.25},																														
    { id_cliente: 59, nombre: 'Ingrid Salazar' , email: 'IngridSalazar@gmail.com', telefono: '(555) 901-2350', direccion: 'Calle 31 # 20-25, Pasto', fecha_registro: 'viernes, 15 de noviembre de 2019', fecha_ultima_visita: 'jueves, 9 de julio de 2020', preferencia_de_mesa: 'Mesa_S19', total_gastado: 480000, comentarios: 'La comida es muy sabrosa.', fecha_nacimiento: 'lunes, 14 de enero de 1991' , tipo_cliente: 'Nuevo', edad: 33, numero_visitas: 8, numero_pedidos: 20, descuento_aplicado: 43700, tiempo_promedio_estancia: 2.00},																														
    { id_cliente: 60, nombre: 'Javier Romero' , email: 'JavierRomero@gmail.com', telefono: '(555) 701-2450', direccion: 'Carrera 31 # 30-12, Pasto', fecha_registro: 'lunes, 2 de diciembre de 2019', fecha_ultima_visita: 'sábado, 22 de agosto de 2020', preferencia_de_mesa: 'Mesa_T20', total_gastado: 350000, comentarios: 'El lugar es muy acogedor.', fecha_nacimiento: 'martes, 25 de octubre de 1994' , tipo_cliente: 'Regular', edad: 30, numero_visitas: 14, numero_pedidos: 13, descuento_aplicado: 38000, tiempo_promedio_estancia: 1.45}																																																				
   ]);

//db.restaurante.find({numero_pedidos: {$nin: [1, 3, 5]}})
//db.restaurante.find({$nor: [{numero_visitas: {$gt: 5}},{total_gastado: {$gte: 80000}}]})
//db.restaurante.find({$or: [{direccion: {$in: ["Calle 12 # 23-45, Pasto", "Avenida Central # 4-56, Pasto"]}},{tipo_cliente: {$nin: ["Regular", "Nuevo"]}}]})
//db.restaurante.find({$and: [{fecha_registro: {$gte: "lunes, 01 de enero de 2024"}},{tipo_cliente: {$ne: "VIP"}},{total_gastado: {$lt: 100000}}]})
//db.restaurante.find({$nor: [{descuento_aplicado: {$in: [10000, 15000, 20000]}},{numero_pedidos: {$gt: 2}}]})
//db.restaurante.find({$nor: [{total_gastado: {$in: [150000, 200000, 250000]}},{numero_visitas: {$gt: 8}}]})
//db.restaurante.find({$and: [{numero_visitas: {$ne: 5}},{edad: {$not: {$gte: 20, $lte: 32}}}]})
//db.restaurante.find({$or: [{numero_pedidos: {$eq: 4}},{descuento_aplicado: {$eq: 15000}}]})
//db.restaurante.find({$nor: [{total_gastado: {$gte: 300000}},{numero_visitas: {$gte: 10}}]})
//db.restaurante.find({total_gastado: {$nin: [50000, 100000, 150000]}})
//db.restaurante.find({$or: [{numero_visitas: {$in: [5, 10, 15]}},{numero_pedidos: {$in: [2, 4, 6]}}]})
//db.restaurante.find({$and: [{tipo_cliente: {$ne: "VIP"}}, {tipo_cliente:{$ne: "Frecuente"}}]})
//db.restaurante.find({$and: [{total_gastado: {$gte: 400000}},{tiempo_promedio_estancia: {$lt: 1.00}}]})
//db.restaurante.find({preferencia_de_mesa: 'Mesa_A1'})
//db.restaurante.find({tiempo_promedio_estancia: {$gt:2.00}})
//db.restaurante.find({descuento_aplicado: {$gte:35000}})
//db.restaurante.find({$and: [{numero_visitas:{$eq:9}}, {total_gastado:{$lte:150000}}]})
//db.restaurante.find({$or: [{total_gastado:{$gte:400000}}, {numero_visitas:{$gt:15}}]})
//db.restaurante.find({$and: [{edad: {$lt:30}}, {numero_visitas: {$gt:5}}]})
//db.restaurante.find({$and: [{numero_pedidos: {$lt:7}}, {total_gastado: {$gt:150000}}]})