db.hotels.insertMany([
{ nombre: 'Bio Habitat Hotel', direccion: 'Carrera 45 # 12B-30, Medellín, Colombia, 50001', clasificacion: 4 , descripcion: 'Hotel boutique ecológico en Medellín, ideal para viajeros que buscan confort y naturaleza.' , capacidadHabitacion: 2 , areaTotal : 500 , tarifaProm: 800000 , numPisos: 2 ,areaHabitacion: 21 , ingresosMensuales: 200000000  },
{ nombre: 'La Pausa Hotelbistró', direccion: 'Calle 72 # 10-15, Bogotá, Colombia, 110211', clasificacion: 3.2 , descripcion: 'Hotel y bistró en Bogotá, combina gastronomía local con alojamiento cómodo en el corazón de la ciudad.' , capacidadHabitacion: 3 , areaTotal : 600 , tarifaProm: 600000 , numPisos: 3 ,areaHabitacion: 30 , ingresosMensuales: 288000000  },
{ nombre: 'Hotel Dann Monasterio', direccion: 'Carrera 43B # 8-28, Cartagena, Colombia, 130001', clasificacion: 4 , descripcion: 'Hotel de lujo en Cartagena con historia y encanto colonial, ubicado en el centro histórico.' , capacidadHabitacion: 2 , areaTotal : 1200 , tarifaProm: 1200000 , numPisos: 1 ,areaHabitacion: 23 , ingresosMensuales: 36000000  },
{ nombre: 'Hotel Puerto Colombia', direccion: 'Carrera 54 # 32-10, Barranquilla, Colombia, 80001', clasificacion: 2 , descripcion: 'Hotel familiar en Barranquilla, cercano a las principales atracciones turísticas y playas.' , capacidadHabitacion: 4 , areaTotal : 900 , tarifaProm: 300000 , numPisos: 5 ,areaHabitacion: 34 , ingresosMensuales: 204000000  },
{ nombre: 'Hotel Central Plaza', direccion: 'Calle 100 # 15-20, Cali, Colombia, 760001', clasificacion: 2.5 , descripcion: 'Hotel moderno en Cali, ubicado cerca de zonas comerciales y financieras de la ciudad.' , capacidadHabitacion: 3 , areaTotal : 800 , tarifaProm: 450000 , numPisos: 7 ,areaHabitacion: 31 , ingresosMensuales: 315000000  },
{ nombre: 'Hotel Casa de la Playa', direccion: 'Carrera 1A # 3-25, Santa Marta, Colombia, 470001', clasificacion: 3 , descripcion: 'Hotel de playa en Santa Marta, perfecto para vacaciones familiares o escapadas románticas.' , capacidadHabitacion: 2 , areaTotal : 1500 , tarifaProm: 500000 , numPisos: 5 ,areaHabitacion: 26 , ingresosMensuales: 260000000  },
{ nombre: 'Hotel Casa del Mar', direccion: 'Calle de la Marina # 5-10, Cartagena, Colombia, 130001', clasificacion: 4.2 , descripcion: 'Hotel boutique en Cartagena con vistas al mar y excelente servicio personalizado.' , capacidadHabitacion: 3 , areaTotal : 1300 , tarifaProm: 1300000 , numPisos: 2 ,areaHabitacion: 30 , ingresosMensuales: 390000000  },
{ nombre: 'Hotel Casa del Sol', direccion: 'Carrera 43A # 12-30, Medellín, Colombia, 50001', clasificacion: 3.5 , descripcion: 'Hotel en Medellín con diseño contemporáneo y acceso a todas las comodidades de la ciudad.' , capacidadHabitacion: 4 , areaTotal : 1000 , tarifaProm: 750000 , numPisos: 6 ,areaHabitacion: 60 , ingresosMensuales: 450000000  },
{ nombre: 'Hotel Casa del Cielo', direccion: 'Calle 63 # 11-15, Bogotá, Colombia, 110211', clasificacion: 3 , descripcion: 'Hotel en Bogotá con habitaciones acogedoras y fácil acceso a las principales atracciones.' , capacidadHabitacion: 2 , areaTotal : 500 , tarifaProm: 500000 , numPisos: 12 ,areaHabitacion: 32 , ingresosMensuales: 384000000  },
{ nombre: 'The Ritz-Carlton, New York, Central Park', direccion: '50 Central Park South, New York, Nueva York, 10019', clasificacion: 4.5 , descripcion: 'Hotel de lujo en Nueva York con vistas espectaculares a Central Park y servicios exclusivos.' , capacidadHabitacion: 3 , areaTotal : 3000 , tarifaProm: 2500000 , numPisos: 9 ,areaHabitacion: 36 , ingresosMensuales: 1620000000  },
{ nombre: 'The Beverly Hills Hotel', direccion: '9641 Sunset Blvd, Beverly Hills, California, 90210', clasificacion: 5 , descripcion: 'Icono de lujo en Beverly Hills, conocido por su servicio impecable y ambiente glamoroso.' , capacidadHabitacion: 3 , areaTotal : 4000 , tarifaProm: 3000000 , numPisos: 30 ,areaHabitacion: 30 , ingresosMensuales: 2700000000  },
{ nombre: 'The Peninsula Beverly Hills', direccion: '9882 S Santa Monica Blvd, Beverly Hills, California, 90210', clasificacion: 4 , descripcion: 'Hotel de lujo con estilo elegante en el corazón de Beverly Hills.' , capacidadHabitacion: 2 , areaTotal : 2500 , tarifaProm: 2800000 , numPisos: 16 ,areaHabitacion: 19 , ingresosMensuales: 1064000000  },
{ nombre: 'The Plaza Hotel', direccion: '768 5th Ave, New York, Nueva York, 10019', clasificacion: 4.6 , descripcion: 'Emblemático hotel en Nueva York, símbolo de elegancia y lujo, famoso por sus vistas y servicio.' , capacidadHabitacion: 4 , areaTotal : 5000 , tarifaProm: 2900000 , numPisos: 22 ,areaHabitacion: 37 , ingresosMensuales: 1600000000  },
{ nombre: 'The Breakers Palm Beach', direccion: '1 S County Rd, Palm Beach, Florida, 33480', clasificacion: 5 , descripcion: 'Resort de lujo en Palm Beach, conocido por su exclusividad y su frente al mar.' , capacidadHabitacion: 5 , areaTotal : 8000 , tarifaProm: 3500000 , numPisos: 13 ,areaHabitacion: 78 , ingresosMensuales: 2730000000  },
{ nombre: 'The Lodge at Vail', direccion: '700 W Lionshead Cir, Vail, CO, 81657', clasificacion: 4 , descripcion: 'Hotel de montaña en Vail, ideal para esquiadores y amantes de la naturaleza.' , capacidadHabitacion: 2 , areaTotal : 1800 , tarifaProm: 2200000 , numPisos: 8 ,areaHabitacion: 17 , ingresosMensuales: 594000000  },
{ nombre: 'The Peninsula Chicago', direccion: '108 E Oak St, Chicago, IL, 60611', clasificacion: 4.2 , descripcion: 'Hotel de lujo en el centro de Chicago, combina confort moderno con elegancia atemporal.' , capacidadHabitacion: 2 , areaTotal : 3000 , tarifaProm: 2600000 , numPisos: 27 ,areaHabitacion: 23 , ingresosMensuales: 774000000  },
{ nombre: 'The Four Seasons Hotel Los Angeles at Beverly Hills', direccion: '300 S Doheny Dr, Beverly Hills, California, 90210', clasificacion: 5 , descripcion: 'Hotel exclusivo en Los Ángeles con vistas impresionantes y servicios de primera clase.' , capacidadHabitacion: 5 , areaTotal : 6000 , tarifaProm: 3800000 , numPisos: 11 ,areaHabitacion: 87 , ingresosMensuales: 2583000000  },
{ nombre: 'The Ritz-Carlton, San Francisco', direccion: '600 Stockton St, San Francisco, California, 94108', clasificacion: 5 , descripcion: 'Hotel de lujo en San Francisco, ubicado en el corazón de la ciudad con vistas al horizonte.' , capacidadHabitacion: 4 , areaTotal : 7000 , tarifaProm: 3200000 , numPisos: 15 ,areaHabitacion: 40 , ingresosMensuales: 1920000000  },
{ nombre: 'The Peninsula New York', direccion: '700 Fifth Ave, New York, Nueva York, 10019', clasificacion: 4.9 , descripcion: 'Hotel de lujo en Nueva York, combina historia y modernidad con vistas a la Quinta Avenida.' , capacidadHabitacion: 4 , areaTotal : 4500 , tarifaProm: 2750000 , numPisos: 18 ,areaHabitacion: 43 , ingresosMensuales: 1188000000  },
{ nombre: 'Hotel Dorado La 70', direccion: 'Calle 70 # 51A-15, Medellín, Colombia, 50010', clasificacion: 3 , descripcion: 'Hotel en Medellín con ambiente acogedor y moderno, perfecto para turistas y viajeros de negocios.' , capacidadHabitacion: 5 , areaTotal : 1600 , tarifaProm: 350000 , numPisos: 2 ,areaHabitacion: 77 , ingresosMensuales: 455000000  },
{ nombre: 'Mashpi Lodge', direccion: 'Vía a Nanegalito, Quito, Ecuador, 170150', clasificacion: 2.5 , descripcion: 'Ecolodge en el corazón de la selva ecuatoriana, ofrece una experiencia única de naturaleza y lujo.' , capacidadHabitacion: 3 , areaTotal : 1200 , tarifaProm: 1800000 , numPisos: 4 ,areaHabitacion: 25 , ingresosMensuales: 630000000  },
{ nombre: 'Hotel Casa Gangotena', direccion: 'Plaza San Francisco, Quito, Ecuador, 170150', clasificacion: 2 , descripcion: 'Hotel boutique en Quito, ubicado en una casa histórica con vistas impresionantes de la ciudad.' , capacidadHabitacion: 2 , areaTotal : 1500 , tarifaProm: 1400000 , numPisos: 8 ,areaHabitacion: 10 , ingresosMensuales: 560000000  },
{ nombre: 'Hotel Boutique La Casona de la Ronda', direccion: 'Calle de la Ronda, Quito, Ecuador, 170150', clasificacion: 1 , descripcion: 'Hotel encantador en Quito, mezcla arquitectura colonial con confort moderno.' , capacidadHabitacion: 4 , areaTotal : 800 , tarifaProm: 850000 , numPisos: 6 ,areaHabitacion: 34 , ingresosMensuales: 442000000  },
{ nombre: 'Hotel Oro Verde Guayaquil', direccion: 'Av. 9 de Octubre y Malecón Simón Bolívar, Guayaquil, Ecuador, 90101', clasificacion: 5 , descripcion: 'Hotel de lujo en Guayaquil, conocido por su hospitalidad y servicio excelente.' , capacidadHabitacion: 5 , areaTotal : 3000 , tarifaProm: 1600000 , numPisos: 10 ,areaHabitacion: 56 , ingresosMensuales: 1680000000  },
{ nombre: 'Hotel Wyndham Guayaquil Puerto Santa Ana', direccion: 'Malecón Simón Bolívar, Guayaquil, Ecuador, 90151', clasificacion: 3.4 , descripcion: 'Hotel en Guayaquil con modernas instalaciones y fácil acceso a las principales atracciones.' , capacidadHabitacion: 5 , areaTotal : 3500 , tarifaProm: 1300000 , numPisos: 3 ,areaHabitacion: 77 , ingresosMensuales: 2001000000  },
{ nombre: 'Hotel Luna Lodge', direccion: 'Montañita, Santa Elena, Ecuador, 90551', clasificacion: 3 , descripcion: 'Hotel ecológico en Montañita, ideal para surfistas y amantes de la naturaleza.' , capacidadHabitacion: 6 , areaTotal : 500 , tarifaProm: 400000 , numPisos: 2 ,areaHabitacion: 90 , ingresosMensuales: 720000000  },
{ nombre: 'Hotel Selina Baños', direccion: 'Baños, Tungurahua, Ecuador, 180101', clasificacion: 4 , descripcion: 'Hotel con ambiente juvenil en Baños, Ecuador, popular entre viajeros aventureros.' , capacidadHabitacion: 3 , areaTotal : 700 , tarifaProm: 500000 , numPisos: 8 ,areaHabitacion: 23 , ingresosMensuales: 345000000  },
{ nombre: 'Hotel Casa del Alfarero', direccion: 'Vilcabamba, Loja, Ecuador, 110150', clasificacion: 2.3 , descripcion: 'Hotel rústico en Vilcabamba, conocido por su tranquilidad y su entorno natural.' , capacidadHabitacion: 4 , areaTotal : 800 , tarifaProm: 300000 , numPisos: 6 ,areaHabitacion: 56 , ingresosMensuales: 360000000  },
{ nombre: 'Hotel Hostería La Casona', direccion: 'Otavalo, Imbabura, Ecuador, 100150', clasificacion: 3 , descripcion: 'Hotel en Otavalo con ambiente colonial, ideal para turistas que visitan el mercado artesanal.' , capacidadHabitacion: 2 , areaTotal : 900 , tarifaProm: 600000 , numPisos: 8 ,areaHabitacion: 12 , ingresosMensuales: 216000000  },
{ nombre: 'Hotel Six Senses Río Palenque', direccion: 'Vía a Tena, Napo, Ecuador, 180601', clasificacion: 1 , descripcion: 'Hotel ecológico en la selva amazónica, combina lujo con conservación ambiental.' , capacidadHabitacion: 5 , areaTotal : 2500 , tarifaProm: 1000000 , numPisos: 5 ,areaHabitacion: 65 , ingresosMensuales: 975000000  },
{ nombre: 'Hotel MX más centro', direccion: 'Calle de Brasil 13, Centro Histórico, Cuauhtémoc, 06000 Ciudad de México, CDMX, Ciudad de México, Mexico, 6000', clasificacion: 4.3 , descripcion: 'Hotel en el centro histórico de Ciudad de México, ideal para turistas y viajeros de negocios.' , capacidadHabitacion: 2 , areaTotal : 1500 , tarifaProm: 850000 , numPisos: 9 ,areaHabitacion: 33 , ingresosMensuales: 495000000  },
{ nombre: 'Hotel Villa del Mar', direccion: 'Calle de Bolivar 14, Centro Histórico, Cuauhtémoc, 06000 Ciudad de México, CDMX, Ciudad de México, Mexico, 6000', clasificacion: 3 , descripcion: 'Hotel económico en Ciudad de México con fácil acceso a zonas comerciales y turísticas.' , capacidadHabitacion: 5 , areaTotal : 2000 , tarifaProm: 700000 , numPisos: 10 ,areaHabitacion: 76 , ingresosMensuales: 1425000000  },
{ nombre: 'Hotel San Francisco León', direccion: 'Blvd. Adolfo López Mateos 1101, Jardines de Jerez, 37150 León, Gto., México, León, Mexico, 37150', clasificacion: 4 , descripcion: 'Hotel moderno en León, Guanajuato, ideal para viajeros de negocios y eventos corporativos.' , capacidadHabitacion: 6 , areaTotal : 3000 , tarifaProm: 1200000 , numPisos: 4 ,areaHabitacion: 100 , ingresosMensuales: 3600000000  },
{ nombre: 'Hotel Fontan Reforma', direccion: 'Av. Paseo de la Reforma 369, Cuauhtémoc, 06500 Ciudad de México, CDMX, Ciudad de México, Mexico, 6500', clasificacion: 3.1 , descripcion: 'Hotel en el Paseo de la Reforma, Ciudad de México, perfecto para turistas y viajeros de negocios.' , capacidadHabitacion: 2 , areaTotal : 1800 , tarifaProm: 650000 , numPisos: 11 ,areaHabitacion: 21 , ingresosMensuales: 388500000  },
{ nombre: 'Hotel Histórico Central', direccion: 'Calle de Tacuba 84, Centro Histórico, Cuauhtémoc, 06000 Ciudad de México, CDMX, Ciudad de México, Mexico, 6000', clasificacion: 2.9 , descripcion: 'Hotel boutique en el corazón de la Ciudad de México, combina historia con modernidad.' , capacidadHabitacion: 3 , areaTotal : 2000 , tarifaProm: 1200000 , numPisos: 8 ,areaHabitacion: 39 , ingresosMensuales: 864000000  },
{ nombre: 'Marquis Reforma Hotel & Spa', direccion: 'Paseo de la Reforma 445, Cuauhtémoc, 06500 Ciudad de México, CDMX, Ciudad de México, Mexico, 6500', clasificacion: 1.8 , descripcion: 'Hotel de lujo en Ciudad de México, con instalaciones de spa y servicios de alta gama.' , capacidadHabitacion: 4 , areaTotal : 4000 , tarifaProm: 1400000 , numPisos: 6 ,areaHabitacion: 43 , ingresosMensuales: 1204000000  },
{ nombre: 'Galería Plaza Reforma', direccion: 'Paseo de la Reforma 425, Cuauhtémoc, 06500 Ciudad de México, CDMX, Ciudad de México, Mexico, 6500', clasificacion: 1 , descripcion: 'Hotel en la Ciudad de México, conocido por su arte y diseño moderno.' , capacidadHabitacion: 2 , areaTotal : 1000 , tarifaProm: 700000 , numPisos: 3 ,areaHabitacion: 28 , ingresosMensuales: 210000000  },
{ nombre: 'Emporio Hotel', direccion: 'Liverpool 16, Juárez, Cuauhtémoc, 06600 Ciudad de México, CDMX, Ciudad de México, Mexico, 6600', clasificacion: 2 , descripcion: 'Hotel clásico en la Ciudad de México, con fácil acceso a las principales atracciones.' , capacidadHabitacion: 6 , areaTotal : 3000 , tarifaProm: 1500000 , numPisos: 9 ,areaHabitacion: 80 , ingresosMensuales: 1800000000  },
{ nombre: 'Sofitel Mexico City Reforma', direccion: 'Paseo de la Reforma 142, Cuauhtémoc, 06500 Ciudad de México, CDMX, Ciudad de México, Mexico, 6500', clasificacion: 4.6 , descripcion: 'Hotel de lujo en el Paseo de la Reforma, combina estilo francés con hospitalidad mexicana.' , capacidadHabitacion: 5 , areaTotal : 5000 , tarifaProm: 2100000 , numPisos: 6 ,areaHabitacion: 86 , ingresosMensuales: 2415000000  },
{ nombre: 'Hotel Catedral', direccion: 'Justo Sierra 16, Centro Histórico, Cuauhtémoc, 06000 Ciudad de México, CDMX, Ciudad de México, Mexico, 6000', clasificacion: 4 , descripcion: 'Hotel en el centro histórico de Ciudad de México, popular entre turistas y viajeros de negocios.' , capacidadHabitacion: 2 , areaTotal : 1000 , tarifaProm: 900000 , numPisos: 9 ,areaHabitacion: 23 , ingresosMensuales: 621000000  }
]);

//db.hotels.find().pretty()
//db.hotels.find({ nombre: { $eq: 'Bio Habitat Hotel' } })
//db.hotels.find({ clasificacion: { $gt: 4 } })
//db.hotels.find({ tarifaProm: { $gte: 1000000 } })
//db.hotels.find({ areaTotal: { $lt: 1000 } })
//db.hotels.find({ capacidadHabitacion: { $lte: 3 } })
//db.hotels.find({ direccion: { $ne: 'Carrera 1A # 3-25, Santa Marta, Colombia, 470001' } })
//db.hotels.find({ ingresosMensuales: { $in: [200000000, 1000000000] } })
//db.hotels.find({ ingresosMensuales: { $nin: [100000000, 5000000000] } })
//db.hotels.find()
//db.hotels.deleteOne({ nombre: 'Hotel Puerto Colombia' })









