db.menu.insertMany([
{ nombrePlato: 'Huevos estrellados', descripcion: 'Huevos fritos acompañados de papas criollas doradas, queso azul cremoso, tocineta crujiente y cebolla caramelizada para un toque dulce.', precio: 24800 , categoria: 'Brunch' , tiempoPreparacion: 10 , calorias : 300 , ingredientesPrincipales: 'Papa criolla, queso azul, tocineta, cebolla caramelizada' , nivelPicante: 'Medio' ,disponibiidad: 15 , popularidad: 231  },
{ nombrePlato: 'Huevos horneados', descripcion: 'Huevos cocidos al horno con una capa de papas crocantes, queso cheddar fundido, mozzarella y tocineta, servido con pan tostado.', precio: 24800 , categoria: 'Brunch' , tiempoPreparacion: 20 , calorias : 450 , ingredientesPrincipales: 'Huevos, papa, queso cheddar, queso mozarella, tocineta, pan' , nivelPicante: 'Suave' ,disponibiidad: 14 , popularidad: 543  },
{ nombrePlato: 'Huevos napolitanos', descripcion: 'Huevos preparados al estilo napolitano, con nachos crujientes, salsa napolitana casera, jamón y queso mozzarella derretido sobre pan.', precio: 24800 , categoria: 'Brunch' , tiempoPreparacion: 15 , calorias : 500 , ingredientesPrincipales: 'Huevos, nachos, salsa napolitana, jamón, queso mozarella, pan' , nivelPicante: 'Medio' ,disponibiidad: 10 , popularidad: 163  },
{ nombrePlato: 'Huevos benedictinos', descripcion: 'Huevos escalfados sobre pan tostado con salchichón cervecero, cubiertos con salsa holandesa cremosa y acompañados de papas doradas.', precio: 24800 , categoria: 'Brunch' , tiempoPreparacion: 15 , calorias : 400 , ingredientesPrincipales: 'Huevos, pan, salchichón cervecero, salsa holandesa, papa' , nivelPicante: 'Suave' ,disponibiidad: 11 , popularidad: 98  },
{ nombrePlato: 'Huevos en tostada de pan', descripcion: 'Tostadas crujientes cubiertas con aguacate fresco, huevos fritos y tocineta crujiente, acompañadas de papas al vapor.', precio: 24800 , categoria: 'Brunch' , tiempoPreparacion: 10 , calorias : 350 , ingredientesPrincipales: 'Huevos, aguacate, tocineta, pan, papa' , nivelPicante: 'Suave' ,disponibiidad: 17 , popularidad: 287  },
{ nombrePlato: 'Huevos caseros', descripcion: 'Huevos revueltos con jamón o tocineta, acompañados de una arepa dorada y pan tostado.', precio: 15900 , categoria: 'Brunch' , tiempoPreparacion: 5 , calorias : 250 , ingredientesPrincipales: 'Huevos, jamón o tocineta, arepa, pan' , nivelPicante: 'Suave' ,disponibiidad: 16 , popularidad: 375  },
{ nombrePlato: 'Sanduche de croissant', descripcion: 'Croissant dorado relleno de queso derretido, tocineta crujiente y un huevo cocido a la perfección.', precio: 17900 , categoria: 'Brunch' , tiempoPreparacion: 5 , calorias : 300 , ingredientesPrincipales: 'Croissant, queso, tocineta, huevo' , nivelPicante: 'Suave' ,disponibiidad: 20 , popularidad: 124  },
{ nombrePlato: 'Pancakes', descripcion: 'Pancakes esponjosos elaborados con harina, leche y huevos, acompañados de mantequilla y frutas frescas opcionales.', precio: 15800 , categoria: 'Brunch' , tiempoPreparacion: 15 , calorias : 350 , ingredientesPrincipales: 'Harina, leche, huevos, mantequilla, frutas (opcional)' , nivelPicante: 'Suave' ,disponibiidad: 16 , popularidad: 643  },
{ nombrePlato: 'Parfait', descripcion: 'Capas de yogurt cremoso, granola crocante y una selección de frutas frescas de temporada.', precio: 12800 , categoria: 'Brunch' , tiempoPreparacion: 5 , calorias : 200 , ingredientesPrincipales: 'Yogurt, granola, frutas' , nivelPicante: 'Suave' ,disponibiidad: 14 , popularidad: 357  },
{ nombrePlato: 'Bowl de fruta', descripcion: 'Variedad de frutas frescas cortadas, ideales para un desayuno ligero y saludable.', precio: 10000 , categoria: 'Brunch' , tiempoPreparacion: 5 , calorias : 150 , ingredientesPrincipales: 'Variedad de frutas' , nivelPicante: 'Suave' ,disponibiidad: 5 , popularidad: 134  },
{ nombrePlato: 'Sanduche de pavo', descripcion: 'Sándwich clásico con pavo ahumado, lechuga fresca, rodajas de tomate y mayonesa, servido en pan artesanal.', precio: 24300 , categoria: 'Sandwich' , tiempoPreparacion: 10 , calorias : 400 , ingredientesPrincipales: 'Pan, pavo, lechuga, tomate, mayonesa' , nivelPicante: 'Suave' ,disponibiidad: 19 , popularidad: 234  },
{ nombrePlato: 'Sanduche de roast beef', descripcion: 'Roast beef jugoso con lechuga fresca, rodajas de tomate y un toque de mostaza, servido en pan crocante.', precio: 24300 , categoria: 'Sandwich' , tiempoPreparacion: 10 , calorias : 450 , ingredientesPrincipales: 'Pan, roast beef, lechuga, tomate, mostaza' , nivelPicante: 'Suave' ,disponibiidad: 11 , popularidad: 865  },
{ nombrePlato: 'Sanduche de pernil', descripcion: 'Pernil asado y sazonado, con lechuga fresca, tomate y mostaza, servido en pan crujiente.', precio: 24300 , categoria: 'Sandwich' , tiempoPreparacion: 10 , calorias : 450 , ingredientesPrincipales: 'Pan, pernil, lechuga, tomate, mostaza' , nivelPicante: 'Suave' ,disponibiidad: 16 , popularidad: 111  },
{ nombrePlato: 'Sanduche de pollo', descripcion: 'Pechuga de pollo asada con lechuga, rodajas de tomate y un toque de mayonesa, en pan fresco.', precio: 24300 , categoria: 'Sandwich' , tiempoPreparacion: 10 , calorias : 400 , ingredientesPrincipales: 'Pan, pollo, lechuga, tomate, mayonesa' , nivelPicante: 'Suave' ,disponibiidad: 17 , popularidad: 109  },
{ nombrePlato: 'Sanduche de jamon y queso', descripcion: 'Sándwich clásico de jamón y queso derretido en pan tostado, ideal para un desayuno rápido.', precio: 15800 , categoria: 'Sandwich' , tiempoPreparacion: 5 , calorias : 300 , ingredientesPrincipales: 'Pan, jamón, queso' , nivelPicante: 'Suave' ,disponibiidad: 12 , popularidad: 90  },
{ nombrePlato: 'Especial Chef + Postre', descripcion: 'Plato especial del chef con carne a la parrilla, vegetales frescos al vapor, y postre del día.', precio: 52400 , categoria: 'Carne' , tiempoPreparacion: 30 , calorias : 850 , ingredientesPrincipales: 'Carne, vegetales, postre' , nivelPicante: 'Suave' ,disponibiidad: 9 , popularidad: 85  },
{ nombrePlato: 'Salmón a la Plancha', descripcion: 'Filete de salmón fresco cocido a la plancha con especias y un toque de limón, acompañado de guarnición.', precio: 58000 , categoria: 'Pescado' , tiempoPreparacion: 25 , calorias : 700 , ingredientesPrincipales: 'Salmón, especias, limón' , nivelPicante: 'Suave' ,disponibiidad: 34 , popularidad: 70  },
{ nombrePlato: 'Lomo en queso asado y miel', descripcion: 'Lomo de res jugoso, cubierto con queso fundido y un toque dulce de miel, ideal para los amantes de lo salado y dulce.', precio: 52400 , categoria: 'Carne' , tiempoPreparacion: 32 , calorias : 900 , ingredientesPrincipales: 'Lomo de res, queso, miel' , nivelPicante: 'Suave' ,disponibiidad: 32 , popularidad: 49  },
{ nombrePlato: 'Tríptico', descripcion: 'Solomillos de res y langostinos sobre una cama de spaguetti, con opción de salsa pesto o napolitana.', precio: 47900 , categoria: 'Carne y Pescado' , tiempoPreparacion: 40 , calorias : 1200 , ingredientesPrincipales: 'Solomillo de res, langostino, spaguetti' , nivelPicante: 'Medio' ,disponibiidad: 56 , popularidad: 123  },
{ nombrePlato: 'Lomo Figo', descripcion: 'Corte de lomo fino acompañado de brochetas de langostinos, servido con nachos crujientes y ensalada dulce.', precio: 47900 , categoria: 'Carne y Pescado' , tiempoPreparacion: 35 , calorias : 1100 , ingredientesPrincipales: 'Lomo fino, langostinos, nachos' , nivelPicante: 'Medio' ,disponibiidad: 43 , popularidad: 187  },
{ nombrePlato: 'Picada Mixta de Carnes', descripcion: 'Variedad de carnes asadas, acompañadas de vegetales al vapor, ideal para compartir.', precio: 46000 , categoria: 'Carne' , tiempoPreparacion: 30 , calorias : 1000 , ingredientesPrincipales: 'Variedad de carnes, vegetales' , nivelPicante: 'Suave' ,disponibiidad: 24 , popularidad: 564  },
{ nombrePlato: 'Costillas San Luis BBQ', descripcion: 'Costillas de cerdo tiernas bañadas en salsa BBQ, servidas con guarnición.', precio: 45900 , categoria: 'Carne' , tiempoPreparacion: 45 , calorias : 950 , ingredientesPrincipales: 'Costillas, salsa BBQ' , nivelPicante: 'Medio' ,disponibiidad: 66 , popularidad: 432  },
{ nombrePlato: 'Milanesa Napolitana', descripcion: 'Milanesa de res, cerdo o pollo, bañada en salsa napolitana y queso gratinado.', precio: 43900 , categoria: 'Carne' , tiempoPreparacion: 30 , calorias : 800 , ingredientesPrincipales: 'Res/Cerdo/Pollo, salsa napolitana' , nivelPicante: 'Suave' ,disponibiidad: 43 , popularidad: 98  },
{ nombrePlato: 'Straccotto al Vino Tinto', descripcion: 'Lomo de res cocido lentamente en vino tinto y hierbas aromáticas, servido con guarnición.', precio: 43800 , categoria: 'Carne' , tiempoPreparacion: 60 , calorias : 950 , ingredientesPrincipales: 'Carne de res, vino tinto, hierbas' , nivelPicante: 'Suave' ,disponibiidad: 15 , popularidad: 56  },
{ nombrePlato: 'Bistecca Maestro', descripcion: 'Corte de res sazonado con especias y cocido a la parrilla, servido con acompañamientos a elección.', precio: 43800 , categoria: 'Carne' , tiempoPreparacion: 55 , calorias : 900 , ingredientesPrincipales: 'Carne de res, especias' , nivelPicante: 'Suave' ,disponibiidad: 34 , popularidad: 43  },
{ nombrePlato: 'Pollo a la Parmesana', descripcion: 'Pechuga de pollo empanizada, cubierta con queso derretido, albahaca fresca y salsa napolitana.', precio: 42900 , categoria: 'Pollo' , tiempoPreparacion: 35 , calorias : 800 , ingredientesPrincipales: 'Pollo, queso, albahaca' , nivelPicante: 'Suave' ,disponibiidad: 54 , popularidad: 11  },
{ nombrePlato: 'Alitas FIGO BBQ', descripcion: 'Alitas de pollo bañadas en salsa BBQ casera, doradas a la perfección.', precio: 34500 , categoria: 'Pollo' , tiempoPreparacion: 25 , calorias : 600 , ingredientesPrincipales: 'Pollo, salsa BBQ' , nivelPicante: 'Picante' ,disponibiidad: 34 , popularidad: 34  },
{ nombrePlato: 'Frutto di mare', descripcion: 'Pizza con mariscos frescos, queso mozzarella y salsa de tomate, cocida al horno.', precio: 64500 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 950 , ingredientesPrincipales: 'Mariscos, salsa de tomate, queso' , nivelPicante: 'Suave' ,disponibiidad: 10 , popularidad: 100  },
{ nombrePlato: 'De Burrata', descripcion: 'Pizza gourmet con burrata fresca, tomate y albahaca, sobre una base de salsa de tomate y queso.', precio: 38500 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 900 , ingredientesPrincipales: 'Burrata, tomate, albahaca' , nivelPicante: 'Suave' ,disponibiidad: 8 , popularidad: 90  },
{ nombrePlato: 'Salami y Cabanos', descripcion: 'Pizza con salami y cabanos, cubierta con queso derretido y salsa de tomate.', precio: 47200 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 1100 , ingredientesPrincipales: 'Salami, cabanos, queso, salsa de tomate' , nivelPicante: 'Medio' ,disponibiidad: 15 , popularidad: 120  },
{ nombrePlato: 'Caprichosa', descripcion: 'Pizza clásica con jamón, champiñones frescos y alcachofas sobre una base de salsa de tomate.', precio: 47200 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 950 , ingredientesPrincipales: 'Jamón, champiñones, alcachofa' , nivelPicante: 'Suave' ,disponibiidad: 12 , popularidad: 110  },
{ nombrePlato: 'Carnes', descripcion: 'Pizza con una variedad de carnes, incluyendo ternera, pollo y salami, sobre una base de salsa de tomate y queso.', precio: 32500 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 1300 , ingredientesPrincipales: 'Ternera, pollo, salami, salsa de tomate' , nivelPicante: 'Picante' ,disponibiidad: 10 , popularidad: 130  },
{ nombrePlato: 'Salteada carnes/verduras', descripcion: 'Pizza con carnes y verduras salteadas, cubiertas con queso y salsa de tomate.', precio: 32500 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 1200 , ingredientesPrincipales: 'Carne, verduras, queso, salsa' , nivelPicante: 'Picante' ,disponibiidad: 11 , popularidad: 125  },
{ nombrePlato: 'Hawaiana', descripcion: 'Pizza con jamón y piña sobre una base de salsa de tomate y queso mozzarella.', precio: 32500 , categoria: 'Pizza' , tiempoPreparacion: 40 , calorias : 900 , ingredientesPrincipales: 'Piña, jamón, queso, salsa de tomate' , nivelPicante: 'Suave' ,disponibiidad: 14 , popularidad: 105  },
{ nombrePlato: 'Empanada añejo con pollo x3', descripcion: 'Empanadas crujientes rellenas de pollo y queso añejo, perfectas para un snack.', precio: 6500 , categoria: 'Empanadas' , tiempoPreparacion: 25 , calorias : 300 , ingredientesPrincipales: 'Pollo, queso añejo' , nivelPicante: 'Suave' ,disponibiidad: 30 , popularidad: 80  },
{ nombrePlato: 'Empanada de añejo guiso x 3', descripcion: 'Empanadas rellenas de guiso de carne y queso añejo, fritas hasta dorar.', precio: 6500 , categoria: 'Empanadas' , tiempoPreparacion: 21 , calorias : 350 , ingredientesPrincipales: 'Guiso, queso añejo' , nivelPicante: 'Suave' ,disponibiidad: 25 , popularidad: 85  },
{ nombrePlato: 'Empanada pollo requeson', descripcion: 'Empanadas rellenas de pollo desmechado y requesón cremoso, con una corteza dorada.', precio: 4500 , categoria: 'Empanadas' , tiempoPreparacion: 20 , calorias : 320 , ingredientesPrincipales: 'Pollo, requesón' , nivelPicante: 'Medio' ,disponibiidad: 22 , popularidad: 75  },
{ nombrePlato: 'Empanada de viento x 2', descripcion: 'Empanadas fritas con relleno de queso suave, con una masa ligera y crujiente.', precio: 6200 , categoria: 'Empanadas' , tiempoPreparacion: 19 , calorias : 300 , ingredientesPrincipales: 'Queso, masa frita' , nivelPicante: 'Picante' ,disponibiidad: 18 , popularidad: 70  },
{ nombrePlato: 'Hamburguesa figo angus', descripcion: 'Hamburguesa de carne Angus jugosa, con queso cheddar, lechuga fresca y tomate, servida en pan brioche.', precio: 32500 , categoria: 'Hamburguesas' , tiempoPreparacion: 42 , calorias : 950 , ingredientesPrincipales: 'Carne Angus, queso, lechuga, tomate' , nivelPicante: 'Suave' ,disponibiidad: 15 , popularidad: 150  },
{ nombrePlato: 'Hamburguesa figo de pollo', descripcion: 'Hamburguesa con pechuga de pollo a la parrilla, queso cheddar, lechuga y tomate, servida en pan brioche.', precio: 27200 , categoria: 'Hamburguesas' , tiempoPreparacion: 31 , calorias : 800 , ingredientesPrincipales: 'Pollo, queso, lechuga, tomate' , nivelPicante: 'Suave' ,disponibiidad: 18 , popularidad: 140  }
]);
//db.menu.find()
//db.menu.find({ nombrePlato: { $eq: 'Huevos estrellados' } })
//db.menu.find({ precio: { $gt: 30000 } })
//db.menu.find({ tiempoPreparacion: { $gte: 30 } })
//db.menu.find({ disponibilidad: { $lt: 10 } })
//db.menu.find({ popularidad: { $lte: 100 } })
//db.menu.find({ nivelPicante: { $ne: 'Suave' } })
//db.menu.find({ calorias: { $in: [200, 300, 400, 500] } })
//db.menu.find({ calorias: { $nin: [400, 500, 600] } })
//db.menu.find({ categoria: 'Brunch' })
//db.menu.updateOne(
//{ nombrePlato: 'Huevos estrellados' },
//{ $set: { precio: 26000 } })
//db.menu.find({ nombrePlato: 'Huevos estrellados' })
