db.shop.insertMany([
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Culottes ajustados y cómodos para ciclismo, diseñados especialmente para mujeres.' , precio: 148592, categoria: 'Ropa de ciclismo para mujer', disponibilidad_inventario: 8, marca: 'Chanel', numero_modelo: 3475, peso: 1, unidades_vendidas: 30, valoracion_promedio: 4.8},														
 { nombre: 'FabHomeDecor Sofá Cama Doble de Tela', descripcion: 'Sofá cama doble de tela, ideal para espacios pequeños y funcionales.' , precio: 148727, categoria: 'Muebles para el hogar', disponibilidad_inventario: 41, marca: 'Zara', numero_modelo: 9821, peso: 20, unidades_vendidas: 15, valoracion_promedio: 3.5},														
 { nombre: 'Vientres AW', descripcion: 'Prenda de estilo casual, adecuada para un look corporativo relajado.' , precio: 135707, categoria: 'Ropa casual corporativa', disponibilidad_inventario: 22, marca: 'Honda', numero_modelo: 5640, peso: 1.5, unidades_vendidas: 45, valoracion_promedio: 4.2},														
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Champú multiusos para perros con extracto de árnica, ideal para el cuidado del pelaje.' , precio: 143557, categoria: 'Cuidado para mascotas', disponibilidad_inventario: 96, marca: 'Reebok', numero_modelo: 1934, peso: 2, unidades_vendidas: 22, valoracion_promedio: 2.9},														
 { nombre: 'Sicons Champú para perros de árnica multiusos', descripcion: 'Pistas de papel con un elegante acabado plateado, perfectas para decoración o eventos.' , precio: 143724, categoria: 'Artículos de decoración', disponibilidad_inventario: 96, marca: 'Reebok', numero_modelo: 2708, peso: 1.2, unidades_vendidas: 18, valoracion_promedio: 4.7},														
 { nombre: 'Eternal Gandhi Super Series Pistas de papel de cristal con acabado plateado', descripcion: 'Conjunto de prendas versátiles, perfectas para un estilo casual o corporativo.' , precio: 129695, categoria: 'Ropa casual corporativa', disponibilidad_inventario: 93, marca: 'Rolex', numero_modelo: 4532, peso: 1.5, unidades_vendidas: 27, valoracion_promedio: 3.8},														
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Estilo casual para el día a día con un toque sofisticado.' , precio: 118915, categoria: 'Ropa casual', disponibilidad_inventario: 74, marca: 'LG', numero_modelo: 1689, peso: 1.8, unidades_vendidas: 50, valoracion_promedio: 4.5},														
 { nombre: 'FabHomeDecor Sofá Cama Doble de Tela', descripcion: 'Vestido estampado para mujer con diseño moderno y elegante.' , precio: 102994, categoria: 'Ropa de mujer', disponibilidad_inventario: 72, marca: 'Vans', numero_modelo: 7234, peso: 1.1, unidades_vendidas: 35, valoracion_promedio: 3.2},														
 { nombre: 'dilli bazaaar Vientres, Casual Corporativo, Casual', descripcion: 'Champú para perros con árbol de té, multiusos para un pelaje limpio y saludable.' , precio: 108742, categoria: 'Cuidado para mascotas', disponibilidad_inventario: 98, marca: 'Apple', numero_modelo: 5091, peso: 2, unidades_vendidas: 40, valoracion_promedio: 4.9},														
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Botella de vacío de 350 ml, ideal para mantener las bebidas frías o calientes por más tiempo.' , precio: 140440, categoria: 'Accesorios para bebidas', disponibilidad_inventario: 80, marca: 'Balenciaga', numero_modelo: 8740, peso: 1, unidades_vendidas: 60, valoracion_promedio: 2.7},														
 { nombre: 'Vientres de Ladela', descripcion: 'Estilo de moda que combina comodidad y elegancia.' , precio: 102388, categoria: 'Moda y estilo', disponibilidad_inventario: 25, marca: 'New Balance', numero_modelo: 6312, peso: 1.7, unidades_vendidas: 10, valoracion_promedio: 4.1},														
 { nombre: 'Carrel Estampado Mujer', descripcion: 'Champú y acondicionador 2 en 1 para perros, diseñado para un cuidado completo.' , precio: 119123, categoria: 'Cuidado para mascotas', disponibilidad_inventario: 89, marca: 'Nike', numero_modelo: 2975, peso: 2, unidades_vendidas: 55, valoracion_promedio: 3.6},														
 { nombre: 'Sicons Champú para perros All Purpose Tea Tree', descripcion: 'Camiseta estampada para niños, perfecta para uso diario.' , precio: 101165, categoria: 'Ropa para niños', disponibilidad_inventario: 5, marca: 'Google', numero_modelo: 1483, peso: 1, unidades_vendidas: 25, valoracion_promedio: 4.4},														
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Zuecos modernos y cómodos, ideales para un estilo casual.' , precio: 125729, categoria: 'Calzado casual', disponibilidad_inventario: 41, marca: 'Apple', numero_modelo: 7906, peso: 3.5, unidades_vendidas: 42, valoracion_promedio: 5},														
 { nombre: 'Botellas de vacío independientes Botella de 350 ml', descripcion: 'Juguete de goma para perros con forma de mancuerna y campana, ideal para entretenimiento.' , precio: 131482, categoria: 'Juguetes para mascotas', disponibilidad_inventario: 83, marca: 'Vans', numero_modelo: 5842, peso: 0.8, unidades_vendidas: 38, valoracion_promedio: 3.3},														
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Conjunto de lencería elegante y delicado, perfecto para bodas.' , precio: 134672, categoria: 'Lencería para bodas', disponibilidad_inventario: 64, marca: 'Dell', numero_modelo: 3410, peso: 1, unidades_vendidas: 30, valoracion_promedio: 4},														
 { nombre: 'FabHomeDecor Sofá Cama Doble de Tela', descripcion: 'Patines cuádruples blancos con acabado brillante, talla 4.5 UK.' , precio: 139971, categoria: 'Patines', disponibilidad_inventario: 13, marca: 'Microsoft', numero_modelo: 9073, peso: 1.2, unidades_vendidas: 20, valoracion_promedio: 4.9},														
 { nombre: 'Estilo Vientre de pie', descripcion: 'Estuche compacto para joyería, ideal para viajes y organización.' , precio: 145188, categoria: 'Almacenamiento de joyería', disponibilidad_inventario: 72, marca: 'Versace', numero_modelo: 2618, peso: 1.5, unidades_vendidas: 48, valoracion_promedio: 3.9},														
 { nombre: 'Carrel Estampado Mujer', descripcion: 'Leggings cómodos y ajustados, ideales para ejercicio o uso casual.' , precio: 126887, categoria: 'Ropa deportiva para mujer', disponibilidad_inventario: 69, marca: 'Adidas', numero_modelo: 4859, peso: 2, unidades_vendidas: 33, valoracion_promedio: 2.5},														
 { nombre: 'FabHomeDecor Sofá Cama Doble de Tela', descripcion: 'Pantalones cargo para hombre, perfectos para actividades al aire libre o estilo casual.' , precio: 139191, categoria: 'Ropa para hombre', disponibilidad_inventario: 95, marca: 'Adidas', numero_modelo: 7934, peso: 1, unidades_vendidas: 17, valoracion_promedio: 4.3},														
 { nombre: 'Sicons Champú Acondicionador Conditoner para Perros', descripcion: 'Planta artificial de rosas con maceta, ideal para decoración interior.' , precio: 126065, categoria: 'Decoración de interiores', disponibilidad_inventario: 45, marca: 'Toyota', numero_modelo: 1290, peso: 1.4, unidades_vendidas: 36, valoracion_promedio: 4.6},														
 { nombre: 'Culottes de ciclismo Alisha Solid para mujer', descripcion: 'Material semi-cosido para lehenga choli con bordados intrincados.' , precio: 117258, categoria: 'Ropa tradicional y bordados', disponibilidad_inventario: 22, marca: 'H&M', numero_modelo: 3045, peso: 1, unidades_vendidas: 29, valoracion_promedio: 3.4},														
 { nombre: 'dongli Camiseta de cuello redondo estampada para niño', descripcion: 'Cuaderno de tamaño A5 con encuadernado en espiral y diseño de banda de música.' , precio: 145789, categoria: 'Papelería', disponibilidad_inventario: 66, marca: 'Google', numero_modelo: 6872, peso: 1.2, unidades_vendidas: 53, valoracion_promedio: 2.8},														
 { nombre: 'Zuecos SWAGGA Mujer', descripcion: 'Set de tres cuadernos diseñados para motivar con frases inspiradoras.' , precio: 107052, categoria: 'Papelería', disponibilidad_inventario: 92, marca: 'Apple', numero_modelo: 5309, peso: 1.8, unidades_vendidas: 12, valoracion_promedio: 4.2},														
 { nombre: 'Mancuerna de goma de perrera con campana - Pequeño juguete de goma de goma para perro', descripcion: 'Chaleco bordado para mujer, perfecto para añadir un toque de estilo a cualquier atuendo.' , precio: 107368, categoria: 'Ropa para mujer', disponibilidad_inventario: 23, marca: 'Lamborghini', numero_modelo: 8421, peso: 1, unidades_vendidas: 44, valoracion_promedio: 3.7},														
 { nombre: 'Glus Conjunto de lencería de boda', descripcion: 'Bolsas de mensajería seguras y duraderas para envíos y almacenamiento.' , precio: 107129, categoria: 'Accesorios para mensajería', disponibilidad_inventario: 43, marca: 'Versace', numero_modelo: 9157, peso: 0.8, unidades_vendidas: 21, valoracion_promedio: 4.8},														
 { nombre: 'Veelys Patines Cuádruples Blancos Brillantes - Talla 4.5 UK', descripcion: 'Abrigo bordado para mujer, elegante y adecuado para el frío.' , precio: 116163, categoria: 'Ropa de mujer', disponibilidad_inventario: 41, marca: 'Dell', numero_modelo: 2843, peso: 1.8, unidades_vendidas: 39, valoracion_promedio: 4},														
 { nombre: 'Estuche de tocador Bulaky Estuche de tocador de joyería', descripcion: 'Bolsa de seda con diseño tradicional, perfecta para ocasiones especiales.' , precio: 103818, categoria: 'Accesorios de moda tradicional', disponibilidad_inventario: 85, marca: 'Dell', numero_modelo: 7604, peso: 1.2, unidades_vendidas: 31, valoracion_promedio: 2.9},														
 { nombre: 'Leggings FDT para mujer', descripcion: 'Peto casual de estilo relajado, ideal para el uso diario.' , precio: 120526, categoria: 'Ropa casual', disponibilidad_inventario: 0, marca: 'Panasonic', numero_modelo: 3908, peso: 1.5, unidades_vendidas: 50, valoracion_promedio: 4.5},														
 { nombre: 'Madcaps C38GR30 Cargos para hombre', descripcion: 'Pantalones cargo para hombre, perfectos para actividades al aire libre o estilo casual.' , precio: 120908, categoria: 'Ropa para hombre', disponibilidad_inventario: 94, marca: 'Samsung', numero_modelo: 2467, peso: 0.7, unidades_vendidas: 19, valoracion_promedio: 3.1},														
 { nombre: 'Planta artificial Bengal Blooms Rose con maceta', descripcion: 'Planta artificial de rosas con maceta, ideal para decoración interior.' , precio: 145449, categoria: 'Decoración de interiores', disponibilidad_inventario: 36, marca: 'Dior', numero_modelo: 5741, peso: 2, unidades_vendidas: 28, valoracion_promedio: 4.7},														
 { nombre: 'Red Indcrown bordada semi-cosida Lehenga Choli Material', descripcion: 'Material semi-cosido para lehenga choli con bordados intrincados.' , precio: 149482, categoria: 'Ropa tradicional y bordados', disponibilidad_inventario: 86, marca: 'Reebok', numero_modelo: 6389, peso: 1.5, unidades_vendidas: 37, valoracion_promedio: 2.6},														
 { nombre: 'Shopmania Music Band A5 Cuaderno Encuadernado en Espiral', descripcion: 'Cuaderno de tamaño A5 con encuadernado en espiral y diseño de banda de música.' , precio: 124139, categoria: 'Papelería', disponibilidad_inventario: 13, marca: 'Chanel', numero_modelo: 4820, peso: 1, unidades_vendidas: 24, valoracion_promedio: 3.9},														
 { nombre: 'Shopmania Music Band A5 Cuaderno Encuadernado en Espiral', descripcion: 'Cuaderno de tamaño A5 con encuadernado en espiral y diseño de banda de música.' , precio: 118878, categoria: 'Papelería', disponibilidad_inventario: 40, marca: 'Adidas', numero_modelo: 7032, peso: 1.8, unidades_vendidas: 41, valoracion_promedio: 4.4},														
 { nombre: 'Tiara Diarios 2016-2017 Diseñador LA Kaarta "TOMANDO ACCIÓN OBTENIENDO RESULTADO" (Set de 3) B5 Notebook Har...', descripcion: 'Set de tres cuadernos diseñados para motivar con frases inspiradoras.' , precio: 123407, categoria: 'Ropa para mujer', disponibilidad_inventario: 81, marca: 'LG', numero_modelo: 1958, peso: 0.8, unidades_vendidas: 34, valoracion_promedio: 4.1},														
 { nombre: 'KAJCI Chaleco de mujer bordado', descripcion: 'Chaleco bordado para mujer, perfecto para añadir un toque de estilo a cualquier atuendo.' , precio: 120381, categoria: 'Accesorios para mensajería', disponibilidad_inventario: 81, marca: 'Intel', numero_modelo: 8914, peso: 1, unidades_vendidas: 23, valoracion_promedio: 5},														
 { nombre: 'Packman 8 x 10 pulgadas Bolsas de seguridad sin chaqueta POD Bolsa de mensajero Bolsa de seguridad', descripcion: 'Bolsas de mensajería seguras y duraderas para envíos y almacenamiento.' , precio: 115069, categoria: 'Ropa de mujer', disponibilidad_inventario: 48, marca: 'Dior', numero_modelo: 3726, peso: 1.2, unidades_vendidas: 49, valoracion_promedio: 3},														
 { nombre: 'Abrigo de mujer bordado Pick Pocket', descripcion: 'Abrigo bordado para mujer, elegante y adecuado para el frío.' , precio: 141961, categoria: 'Accesorios de moda tradicional', disponibilidad_inventario: 9, marca: 'Tesla', numero_modelo: 6097, peso: 1.3, unidades_vendidas: 32, valoracion_promedio: 4.8},														
 { nombre: 'Pez Ángel Seda Potali Potli', descripcion: 'Bolsa de seda con diseño tradicional, perfecta para ocasiones especiales.' , precio: 113662, categoria: 'Ropa casual', disponibilidad_inventario: 33, marca: 'Versace', numero_modelo: 7451, peso: 1.5, unidades_vendidas: 26, valoracion_promedio: 4.3},														
 { nombre: 'Peto de Oye Boy', descripcion: 'Peto casual de estilo relajado, ideal para el uso diario.' , precio: 106677, categoria: 'Ropa casual', disponibilidad_inventario: 41, marca: 'Under Armour', numero_modelo: 2938, peso: 1.8, unidades_vendidas: 47, valoracion_promedio: 3.5}														
]);

//db.shop.updateOne({ nombre: 'Culottes de ciclismo Alisha Solid para mujer' },  { $set: { nombre: 'Sabanas tipo summer', descripcion: 'Sabanas para dormri tranquilamente', precio: 100000, categoria: 'Muebles', disponibilidad_inventario: 90, marca: 'Summer', numero_modelo: 7000, peso: 0.5, unidades_vendidas: 10, valoracion_promedio: 5}})
//db.shop.find({nombre: {$eq: "Sabanas tipo summer"}}) 
//db.shop.find({unidades_vendidas: {$nin :[20, 30, 40, 50, 60]}})
//db.shop.find({valoracion_promedio: {$in: [4, 5]}})
//db.shop.find({unidades_vendidas: {$ne: 30}})
//db.shop.find({peso: {$lte: 1}})
//db.shop.find({numero_modelo: {$lt: 2000}})
//db.shop.find({disponibilidad_inventario: {$gte: 80}})
//db.shop.find({precio: {$gt: 140000}})
//db.shop.find({nombre: {$eq: 'Peto de Oye Boy'}})
