db.university.insertMany([
 { nombre_materia: 'Fundamento Matemático', codigo_materia: 'X1010' , descripcion: 'Introduce conceptos básicos de aritmética, álgebra y geometría, con el objetivo de fortalecer el razonamiento lógico. Requiere nociones elementales de matemáticas.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Marcela', aulas_asignadas: '601', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 3.2},														
 { nombre_materia: 'Lógica Matemática', codigo_materia: 'Z1020' , descripcion: 'Estudio formal de proposiciones, conectores y sistemas deductivos para el desarrollo de habilidades de razonamiento matemático. Requiere conocimientos previos en fundamentos matemáticos.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 0, profesores_responsables: 'Zuleta', aulas_asignadas: '602', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 4.8},														
 { nombre_materia: 'Algoritmos y Programación I', codigo_materia: 'Q1030' , descripcion: 'Enseña los principios básicos de la programación y la resolución de problemas mediante algoritmos. Requiere lógica matemática básica.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Alvaro', aulas_asignadas: '601', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 3.5},														
 { nombre_materia: 'Introducción a la Ingeniería', codigo_materia: 'B1040' , descripcion: 'Proporciona una visión general de las disciplinas de ingeniería, su impacto social y su ética. No tiene requisitos previos.', creditos: 1, horas_clases_teoricas: 48, horas_clases_practicas: 0, profesores_responsables: 'Magda', aulas_asignadas: '604', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 4.1},														
 { nombre_materia: 'Lectoescritura Investigativa', codigo_materia: 'T1050' , descripcion: 'Desarrolla habilidades en la lectura crítica y redacción académica para la investigación. Requiere competencias básicas de lectura y escritura.', creditos: 1, horas_clases_teoricas: 48, horas_clases_practicas: 0, profesores_responsables: 'Carlos', aulas_asignadas: '602', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 3.7},														
 { nombre_materia: 'Pensamiento Filosófico', codigo_materia: 'N1060' , descripcion: 'Explora las principales corrientes filosóficas y su influencia en el pensamiento contemporáneo. No tiene requisitos previos.', creditos: 2, horas_clases_teoricas: 0, horas_clases_practicas: 96, profesores_responsables: 'Eyner', aulas_asignadas: '601', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 3.9},														
 { nombre_materia: 'Electiva Complementaria 1', codigo_materia: 'P1070' , descripcion: 'Materia electiva de libre elección que complementa el perfil académico del estudiante. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 0, profesores_responsables: 'Mauricio', aulas_asignadas: '603', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 4.4},														
 { nombre_materia: 'Electiva General 1', codigo_materia: 'W1080' , descripcion: 'Materia de enfoque general que expande el conocimiento interdisciplinario del estudiante. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 9, profesores_responsables: 'Erick', aulas_asignadas: '603', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 3.3},														
 { nombre_materia: 'Curso de Desarrollo Humano', codigo_materia: 'V1090' , descripcion: 'Fomenta el crecimiento personal y profesional mediante la reflexión sobre temas de identidad y valores. No tiene requisitos previos.', creditos: 1, horas_clases_teoricas: 0, horas_clases_practicas: 48, profesores_responsables: 'Andres', aulas_asignadas: '602', prerrequisitos: 'Titulo bachiller', promedio_calificaciones: 4.6},														
 { nombre_materia: 'Algebra Lineal', codigo_materia: 'M1100' , descripcion: 'Estudia sistemas de ecuaciones lineales, matrices y espacios vectoriales, fundamentales para diversas aplicaciones en ingeniería. Requiere fundamentos matemáticos.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Marcela', aulas_asignadas: '601', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 3.8},														
 { nombre_materia: 'Calculo Diferencial', codigo_materia: 'Y2010' , descripcion: 'Introduce el estudio de límites, derivadas y su aplicación en problemas de cambio. Requiere fundamentos de álgebra y trigonometría.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Marcela', aulas_asignadas: '603', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 4},														
 { nombre_materia: 'Algoritmos y Programación II', codigo_materia: 'L2020' , descripcion: 'Continuación de Algoritmos I, enfocada en estructuras de datos y resolución avanzada de problemas. Requiere Algoritmos y Programación I.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Mauricio', aulas_asignadas: '603', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 3.6},														
 { nombre_materia: 'Mecánica', codigo_materia: 'R2030' , descripcion: 'Estudia el movimiento de cuerpos bajo la acción de fuerzas, fundamental en la física clásica. Requiere cálculo diferencial y fundamentos de física.', creditos: 3, horas_clases_teoricas: 144, horas_clases_practicas: 0, profesores_responsables: 'Nicolas', aulas_asignadas: 'Alvernia', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 4.2},														
 { nombre_materia: 'Epistemología Especifica', codigo_materia: 'K2040' , descripcion: 'Analiza el conocimiento científico y los métodos propios de las ciencias exactas. Requiere pensamiento filosófico.', creditos: 1, horas_clases_teoricas: 48, horas_clases_practicas: 0, profesores_responsables: 'Zuleta', aulas_asignadas: '604', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 4.9},														
 { nombre_materia: 'Humanismo Cristiano', codigo_materia: 'J2050' , descripcion: 'Aborda el estudio de la ética y los valores desde una perspectiva cristiana. No tiene requisitos previos.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 0, profesores_responsables: 'Eyner', aulas_asignadas: '604', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 3.4},														
 { nombre_materia: 'Electiva Complementaria 2', codigo_materia: 'D2060' , descripcion: 'Otra materia electiva que complementa el currículo, permitiendo flexibilidad académica. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Mauricio', aulas_asignadas: '602', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 4.3},														
 { nombre_materia: 'Electiva General 2', codigo_materia: 'H2070' , descripcion: 'Segunda electiva general para ampliar el conocimiento en áreas fuera del campo principal de estudio. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Parra', aulas_asignadas: '602', prerrequisitos: 'Primer semestre aprobado', promedio_calificaciones: 4.7},														
 { nombre_materia: 'Matemáticas Discretas', codigo_materia: 'F2080' , descripcion: 'Introduce el estudio de estructuras matemáticas fundamentales en ciencias de la computación, como grafos y teoría de conjuntos. Requiere lógica matemática.', creditos: 2, horas_clases_teoricas: 0, horas_clases_practicas: 96, profesores_responsables: 'Mauricio', aulas_asignadas: '602', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 3.1},														
 { nombre_materia: 'Cálculo Integral', codigo_materia: 'G2090' , descripcion: 'Estudia las integrales y su aplicación en áreas como el cálculo de áreas y volúmenes. Requiere cálculo diferencial.', creditos: 2, horas_clases_teoricas: 0, horas_clases_practicas: 96, profesores_responsables: 'Marcela', aulas_asignadas: '601', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 4.5},														
 { nombre_materia: 'Métodos Numéricos', codigo_materia: 'C2100' , descripcion: 'Introduce técnicas numéricas para la resolución aproximada de ecuaciones y problemas matemáticos complejos mediante métodos computacionales. Requiere cálculo diferencial e integral.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Mauricio', aulas_asignadas: '601', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 3.9},														
 { nombre_materia: 'Algoritmos y Programación III', codigo_materia: 'A3010' , descripcion: 'Profundiza en la programación con un enfoque en técnicas avanzadas y algoritmos complejos. Requiere Algoritmos y Programación II.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Daniel', aulas_asignadas: '603', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 3},														
 { nombre_materia: 'Electricidad y Magnetismo', codigo_materia: 'E3020' , descripcion: 'Estudia los principios fundamentales de la electricidad, el magnetismo y sus aplicaciones en ingeniería. Requiere conocimientos básicos de física y cálculo.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Nicolas', aulas_asignadas: 'Alvernia', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 4.6},														
 { nombre_materia: 'Ética Profesional', codigo_materia: 'U3030' , descripcion: 'Explora los principios éticos y responsabilidades profesionales en el campo de la ingeniería y otras disciplinas. No tiene requisitos previos.', creditos: 2, horas_clases_teoricas: 0, horas_clases_practicas: 96, profesores_responsables: 'Juan', aulas_asignadas: '603', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 3.7},														
 { nombre_materia: 'Electiva Complementaria 3', codigo_materia: 'I3040' , descripcion: 'Materia electiva que complementa el currículo académico, permitiendo al estudiante explorar nuevas áreas de conocimiento. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 0, horas_clases_practicas: 96, profesores_responsables: 'Erick', aulas_asignadas: '604', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 4.2},														
 { nombre_materia: 'Electiva General 3', codigo_materia: 'O3050' , descripcion: 'Materia general de libre elección que amplía el conocimiento interdisciplinario del estudiante. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 0, profesores_responsables: 'Erick', aulas_asignadas: '604', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 3.8},														
 { nombre_materia: 'Ecuaciones Diferenciales', codigo_materia: 'S3060' , descripcion: 'Introduce el estudio de ecuaciones diferenciales y sus aplicaciones en el modelado de fenómenos físicos y de ingeniería. Requiere cálculo integral.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 0, profesores_responsables: 'Marcela', aulas_asignadas: '602', prerrequisitos: 'Segundo semestre aprobado', promedio_calificaciones: 4},														
 { nombre_materia: 'Maquinas Eléctricas', codigo_materia: 'Z3070' , descripcion: 'Estudia los principios de operación de las máquinas eléctricas, como motores y generadores. Requiere conocimientos en electricidad y magnetismo.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Nicolas', aulas_asignadas: 'Alvernia', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 3.5},														
 { nombre_materia: 'Estructura de Datos I', codigo_materia: 'Q3080' , descripcion: 'Introduce estructuras de datos básicas, como pilas, colas y listas, fundamentales en el desarrollo de software eficiente. Requiere Algoritmos y Programación II.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Parra', aulas_asignadas: '602', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 4.3},														
 { nombre_materia: 'Interacción Hombre Máquina', codigo_materia: 'B3090' , descripcion: 'Aborda la interacción entre humanos y sistemas computacionales, buscando mejorar la usabilidad y experiencia de usuario. Requiere nociones de programación.', creditos: 3, horas_clases_teoricas: 144, horas_clases_practicas: 0, profesores_responsables: 'Mauricio', aulas_asignadas: '603', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 4.1},														
 { nombre_materia: 'Probabilidad y Estadística Descriptiva', codigo_materia: 'T3100' , descripcion: 'Introduce los conceptos básicos de probabilidad y estadística, con un enfoque en la descripción y análisis de datos. Requiere fundamentos matemáticos.', creditos: 3, horas_clases_teoricas: 144, horas_clases_practicas: 0, profesores_responsables: 'Marcela', aulas_asignadas: '601', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 3.9},														
 { nombre_materia: 'Electiva Complementaria 4', codigo_materia: 'N4010' , descripcion: 'Otra materia electiva complementaria que permite al estudiante explorar áreas adicionales de su interés académico. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Villalba', aulas_asignadas: '602', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 4.4},														
 { nombre_materia: 'Electiva General 4', codigo_materia: 'P4020' , descripcion: 'Electiva general que expande el conocimiento del estudiante en disciplinas diversas fuera de su área principal. Los requisitos dependen de la electiva seleccionada.', creditos: 1, horas_clases_teoricas: 24, horas_clases_practicas: 24, profesores_responsables: 'Mauricio', aulas_asignadas: '603', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 3.6},														
 { nombre_materia: 'Teoría de Bases de Datos', codigo_materia: 'W4030' , descripcion: 'Estudia los principios fundamentales de las bases de datos, su diseño y manejo eficiente de la información. Requiere estructuras de datos básicas.', creditos: 3, horas_clases_teoricas: 0, horas_clases_practicas: 144, profesores_responsables: 'Carrera', aulas_asignadas: '603', prerrequisitos: 'Tercer semestre aprobado', promedio_calificaciones: 4.7},														
 { nombre_materia: 'Estructura de Datos II', codigo_materia: 'V4040' , descripcion: 'Continúa el estudio de estructuras de datos, profundizando en árboles, grafos y algoritmos de búsqueda y ordenamiento. Requiere Estructura de Datos I.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Parra', aulas_asignadas: '602', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 3.2},														
 { nombre_materia: 'Estadística Inferencial', codigo_materia: 'M4050' , descripcion: 'Introduce técnicas de inferencia estadística para la estimación y prueba de hipótesis a partir de muestras de datos. Requiere probabilidad y estadística descriptiva.', creditos: 3, horas_clases_teoricas: 72, horas_clases_practicas: 72, profesores_responsables: 'Marcela', aulas_asignadas: '601', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 4.5},														
 { nombre_materia: 'Electrónica Digital', codigo_materia: 'X4060' , descripcion: 'Estudia los fundamentos de la electrónica digital, enfocada en circuitos lógicos y sistemas binarios. Requiere conocimientos básicos de electricidad.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Villalba', aulas_asignadas: '604', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 3.1},														
 { nombre_materia: 'Procesos de Investigación I', codigo_materia: 'L4070' , descripcion: 'Introduce las metodologías y enfoques básicos para la investigación científica, desde la formulación de problemas hasta la recolección de datos. No tiene requisitos previos.', creditos: 1, horas_clases_teoricas: 24, horas_clases_practicas: 24, profesores_responsables: 'Zuleta', aulas_asignadas: '602', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 4.8},														
 { nombre_materia: 'Formulación y Gestión de Proyectos', codigo_materia: 'R4080' , descripcion: 'Proporciona herramientas para la formulación y gestión eficiente de proyectos en diversas áreas, desde su planificación hasta su ejecución. No tiene requisitos previos.', creditos: 2, horas_clases_teoricas: 96, horas_clases_practicas: 0, profesores_responsables: 'Wilson', aulas_asignadas: '602', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 3.3},														
 { nombre_materia: 'Electiva Complementaria 5', codigo_materia: 'K4090' , descripcion: 'Materia electiva complementaria avanzada que permite explorar áreas más específicas dentro del campo académico. Los requisitos dependen de la electiva seleccionada.', creditos: 2, horas_clases_teoricas: 33, horas_clases_practicas: 33, profesores_responsables: 'Daniel', aulas_asignadas: '603', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 4},														
 { nombre_materia: 'Electiva General 5', codigo_materia: 'J4100' , descripcion: 'Otra electiva general que amplía el conocimiento del estudiante en áreas fuera de su campo principal de estudio. Los requisitos dependen de la electiva seleccionada.', creditos: 1, horas_clases_teoricas: 24, horas_clases_practicas: 24, profesores_responsables: 'Wilson', aulas_asignadas: '601', prerrequisitos: 'Cuarto semestre aprobado', promedio_calificaciones: 3.4},														
]);

//db.university.deleteOne({ nombre_materia: 'Electiva General 5' })
//db.university.find({nombre_materia: {$eq: "Electiva General 5"}}) 
//db.university.find()
//db.university.find({promedio_calificaciones: {$nin :[4, 4.5, 4.6, 4.7, 4.8, 4.9, 5]}})
//db.university.find({aulas_asignadas: {$in: ['Alvernia', '604']}})
//db.university.find({profesores_responsables: {$ne: 'Mauricio'}})
//db.university.find({codigo_materia: {$lte: 'J4100'}})
//db.university.find({horas_clases_practicas: {$lt: 72}})
//db.university.find({horas_clases_teoricas: {$gte: 72}})
//db.university.find({creditos: {$gt: 2}})
//db.university.find({nombre_materia: {$eq: 'Teoría de Bases de Datos'}})

